// TOJAIL below is same as JOURNEY except has the north from gallows  *Styx* 4/1/02
#define SCITY "/d/shadow/room/city/"

#define JOURNEY ([\
SCITY+"trainer":"east",\
SCITY+"southgate":"north",\
SCITY+"forkroad":"west",\
SCITY+"sroad":"south",\
SCITY+"smroad":"south",\
SCITY+"mroad":"south",\
"/d/guilds/fist/hall/guild1":"west",\
SCITY+"nroad":"south",\
SCITY+"tb_rd_tb":"south",\
SCITY+"troopb1":"west",\
SCITY+"troopb2":"east",\
SCITY+"th_rd_sc":"south",\
SCITY+"townhall":"west",\
SCITY+"scribe":"east",\
SCITY+"ch_rd_mu":"south",\
SCITY+"healer":"west",\
SCITY+"cguild/paladin/wood":"east",\
SCITY+"cguild/paladin/fountain":"east",\
SCITY+"al_rd_ag":"south",\
SCITY+"alchemist":"west",\
SCITY+"adventure":"east",\
SCITY+"gs_rd_bk":"south",\
SCITY+"bank":"west",\
SCITY+"gs_store":"east",\
"/d/shadowgate/adv_main":"southeast",\
"/d/shadowgate/ombud_hall":"up",\
"/d/shadowgate/abyss":"portal",\
"/d/shadowgate/arch/2nd_floor":"down",\
"/d/shadow/room/main/garrison5":"southeast",\
SCITY+"cguild/fighter/ac_fighter":"west",\
SCITY+"cguild/fighter/fighter":"out",\
"/d/shadow/room/main/garrison4":"south",\
SCITY+"library":"east",\
"/d/shadow/room/main/garrison3":"south",\
SCITY+"hotel":"west",\
"/d/shadow/room/main/garrison2":"south",\
SCITY+"troopb4":"east",\
"/d/shadow/room/main/garrison1":"south",\
SCITY+"troopb3":"west",\
"/d/shadow/room/main/northcross":"south",\
"/d/shadow/room/main/northgate":"south",\
SCITY+"eroad1":"west",\
SCITY+"eroad2":"southeast",\
SCITY+"eroad3":"southeast",\
SCITY+"weapon":"west",\
SCITY+"eroad4":"south",\
SCITY+"eroad5":"south",\
SCITY+"egeroad":"south",\
SCITY+"eroad6":"south",\
SCITY+"eroad7":"south",\
SCITY+"eroad8":"south",\
SCITY+"eroad9":"south",\
SCITY+"eroad10":"south",\
SCITY+"eroad11":"south",\
SCITY+"eroad12":"south",\
SCITY+"eroad13":"south",\
SCITY+"eroad14":"south",\
SCITY+"eroad15":"south",\
SCITY+"eroad16":"south",\
SCITY+"eroad16":"southwest",\
SCITY+"druids/park1":"west",\
SCITY+"druids/park1_2":"west",\
SCITY+"druids/park2":"north",\
SCITY+"eroad17":"southwest",\
SCITY+"eroad18":"southwest",\
SCITY+"eroad19":"southwest",\
SCITY+"wroad19":"southeast",\
SCITY+"wroad18":"southeast",\
SCITY+"wroad17":"southeast",\
SCITY+"wroad16":"southeast",\
SCITY+"cguild/thief/warehouse":"east",\
SCITY+"wroad15":"south",\
SCITY+"wroad14":"south",\
SCITY+"wroad13":"south",\
SCITY+"wroad12":"south",\
SCITY+"church":"west",\
SCITY+"wroad11":"south",\
SCITY+"wroad10":"south",\
SCITY+"wroad9":"south",\
SCITY+"cguild/antipaladin/anti1":"east",\
SCITY+"cguild/antipaladin/anti2":"east",\
SCITY+"wroad8":"south",\
SCITY+"wroad7":"south",\
SCITY+"wroad6":"south",\
SCITY+"wgwroad":"south",\
SCITY+"wroad5":"south",\
SCITY+"wroad4":"south",\
SCITY+"wroad3":"southwest",\
SCITY+"armor":"east",\
SCITY+"wroad2":"southwest",\
SCITY+"wroad1":"east",\
SCITY+"wgroad2":"east",\
SCITY+"wgroad1":"east",\
SCITY+"westgate":"east",\
SCITY+"wltower":"north",\
SCITY+"wnltower":"south",\
SCITY+"innroad1":"northwest",\
SCITY+"innroad2":"northwest",\
SCITY+"inn":"northwest",\
SCITY+"stable":"south",\
SCITY+"cguild/cavalier/guild1":"out",\
SCITY+"egroad2":"west",\
SCITY+"bounty":"north",\
SCITY+"moffice":"west",\
SCITY+"egroad1":"west",\
SCITY+"eastgate":"west",\
SCITY+"barroad1":"northeast",\
SCITY+"barroad2":"northeast",\
SCITY+"bar":"northeast",\
SCITY+"enltower":"south",\
SCITY+"eltower":"north",\
])

#define TOJAIL ([\
SCITY+"gallows":"north",\
SCITY+"forkroad":"west",\
SCITY+"sroad":"south",\
SCITY+"smroad":"south",\
SCITY+"mroad":"south",\
"/d/guilds/fist/hall/guild1":"west",\
SCITY+"nroad":"south",\
"/d/player_houses/stefano/postoffice":"east",\
SCITY+"tb_rd_tb":"south",\
SCITY+"troopb1":"west",\
SCITY+"troopb2":"east",\
SCITY+"th_rd_sc":"south",\
SCITY+"townhall":"west",\
SCITY+"scribe":"east",\
SCITY+"ch_rd_mu":"south",\
SCITY+"healer":"west",\
SCITY+"cguild/paladin/wood":"east",\
SCITY+"cguild/paladin/fountain":"east",\
SCITY+"al_rd_ag":"south",\
SCITY+"alchemist":"west",\
SCITY+"adventure":"east",\
SCITY+"gs_rd_bk":"south",\
SCITY+"bank":"west",\
SCITY+"gs_store":"east",\
"/d/shadowgate/adv_main":"southeast",\
"/d/shadowgate/ombud_hall":"up",\
"/d/shadowgate/abyss":"portal",\
"/d/shadowgate/arch/2nd_floor":"down",\
"/d/shadow/room/main/garrison5":"southeast",\
SCITY+"cguild/fighter/ac_fighter":"west",\
SCITY+"cguild/fighter/fighter":"out",\
"/d/shadow/room/main/garrison4":"south",\
SCITY+"library":"east",\
"/d/shadow/room/main/garrison3":"south",\
SCITY+"hotel":"west",\
"/d/shadow/room/main/garrison2":"south",\
SCITY+"troopb4":"east",\
"/d/shadow/room/main/garrison1":"south",\
SCITY+"troopb3":"west",\
"/d/shadow/room/main/northcross":"south",\
"/d/shadow/room/main/northgate":"south",\
"/d/shadow/room/main/northgate":"south",\
SCITY+"eroad1":"west",\
SCITY+"eroad2":"southeast",\
SCITY+"eroad3":"southeast",\
SCITY+"weapon":"west",\
SCITY+"eroad4":"south",\
SCITY+"eroad5":"south",\
SCITY+"egeroad":"south",\
SCITY+"eroad6":"south",\
SCITY+"eroad7":"south",\
SCITY+"eroad8":"south",\
SCITY+"eroad9":"south",\
SCITY+"eroad10":"south",\
SCITY+"eroad11":"south",\
SCITY+"eroad12":"south",\
SCITY+"eroad13":"south",\
SCITY+"eroad14":"south",\
SCITY+"eroad15":"south",\
SCITY+"eroad16":"south",\
SCITY+"eroad16":"southwest",\
SCITY+"druids/park1":"west",\
SCITY+"druids/park1_2":"west",\
SCITY+"druids/park2":"north",\
SCITY+"eroad17":"southwest",\
SCITY+"eroad18":"southwest",\
SCITY+"eroad19":"southwest",\
SCITY+"wroad19":"southeast",\
SCITY+"wroad18":"southeast",\
SCITY+"wroad17":"southeast",\
SCITY+"wroad16":"southeast",\
SCITY+"cguild/thief/warehouse":"east",\
SCITY+"wroad15":"south",\
SCITY+"wroad14":"south",\
SCITY+"wroad13":"south",\
SCITY+"wroad12":"south",\
SCITY+"church":"west",\
SCITY+"wroad11":"south",\
SCITY+"wroad10":"south",\
SCITY+"wroad9":"south",\
SCITY+"cguild/antipaladin/anti1":"east",\
SCITY+"cguild/antipaladin/anti2":"east",\
SCITY+"wroad8":"south",\
SCITY+"wroad7":"south",\
SCITY+"wroad6":"south",\
SCITY+"wgwroad":"south",\
SCITY+"wroad5":"south",\
SCITY+"wroad4":"south",\
SCITY+"wroad3":"southwest",\
SCITY+"armor":"east",\
SCITY+"wroad2":"southwest",\
SCITY+"wroad1":"east",\
SCITY+"wgroad2":"east",\
SCITY+"wgroad1":"east",\
SCITY+"westgate":"east",\
SCITY+"wltower":"north",\
SCITY+"wnltower":"south",\
SCITY+"innroad1":"northwest",\
SCITY+"innroad2":"northwest",\
SCITY+"inn":"northwest",\
SCITY+"stable":"south",\
SCITY+"cguild/cavalier/guild1":"out",\
SCITY+"egroad2":"west",\
SCITY+"bounty":"north",\
SCITY+"moffice":"west",\
SCITY+"egroad1":"west",\
SCITY+"eastgate":"west",\
SCITY+"barroad1":"northeast",\
SCITY+"barroad2":"northeast",\
SCITY+"bar":"northeast",\
SCITY+"enltower":"south",\
SCITY+"eltower":"north",\
])
