#define HUMAN_NAMES_10 ({ "Diastrad","Burchabel","Ightbankin","Trerard","Danskelqua","Turmorir","Tiserim","Lorlyetai","Swakinas","Fostight","Kalvornys","Styissgha","Enosdyn","Solerenth","Angorelm","Yerurnbel","Clamoran","Blianunt","Jatheng",\
    "Straigack","Zitonhin","Schidrapol","Reelrad","Dynkelche","Clilight","Laitgha","Adpolray","Nyashden","Sleemang","Hinangach","Sutinhon","Angarton","Lyathdra","Phaircha","Tonania","Sillold","Cheackcha","Waysild","Garaldeng","Aughrothton",\
    "Yauton","Mekelper","Reyfpol","Adtherach","Niessul","Dukelshy","Crornal","Doentin","Untanit","Sienver","Natold","Mittan","Themosing","Chreanrad","Toruntrad","Goudther","Daendech","Noisiss","Duissath","Stoissess","Laichund","Zurtan",\
    "Diardkal","Slealetas","Ateldwor","Smunnray","Ashustther","Hatonrak","Chadynath","Queallar","Umeldtin","Nalraydra","Tiswor","Triurnver","Garpercha","Koitper","Echackrak","Swotasshy","Ricust","Ricdar","Roolroth","Elmoner","Zhelsul",\
    "Totray","Reiaum","Aughtasar","Netasild","Smofshy","Nophos","Ustcheiss","Kimmosald","Tryoldom","Zhuvos","Duiwild","Tenwor","Latyer","Zaquasay","Naylkin","Reuseld","Quasamorm","Swuenris","Morcheaugh","Nukimril","Croerom","Schoetis",\
    "Suchaen","Jeychelm","Undlyerak","Strirothsam","Ghaqueche","Buchale","Saultenth","Dynaledel","Nyrayver","Schiwarit","Cluwaright","Rilenet","Ingvoress","Dralyeech", })
#define HUMAN_NAMES_20 ({ "Clurisold","Loosard","Ormlyebel","Aromler","Thrilorkin","Oughustath","Densamough","Craycther","Thertaiend","Rudelves","Enurnmos","Crisscer","Sikalenth","Lleynnsam","Ghahinech","Ineinaugh","Osuntkal","Inetontor",\
    "Lleunskel","Lauqend","Swuenshy","Lerbanther","Hinetash","Shybanvor","Erineunt","Cimshy","Hofend","Hinisem","Braitunt","Radialer","Stuengdyn","Tayskel","Yevesad","Driangrad","Neertem","Kyquaryn","Cheeddar","Drardest","Rakoughen",\
    "Zuasest","Risendny","Perkimaugh","Trealton","Bluvorend","Verangskel","Geuzild","Hatghaton","Onghaqua","Bonyess","Dyndanler","Burvesard","Herdang","Shytondyn","Riankim","Swidyning","Moraddyn","Zhythersam","Yochany","Sulildban",\
    "Stoperkim","Rayerech","Ririsvor","Denryngar","Quaosach","Sinehin","Hohpol","Citmor","Oughuskskel","Niackon","Ildechenth","Taiustyer","Traissver","Snoraydar","Leonem","Chraltbur","Streanhon","Kyustrak","Vorodtin","Paburbel",\
    "Sonem","Augherlor","Nootkin","Siafet","Smeathsul","Suintenth","Turechskel","Cheundet","Lloormorm","Phohest","Cerosiss","Nomer","Rassaw","Smoerras","Llalan","Rankelor","Tratonnal","Doinaine","Adageer","Draewray","Reeness",\
    "Throaughash","Jounnad","Lyerilath","Chribanroth","Rystin","Teitough","Voodray","Kimawtas","Droildight","Sulyerad","Inatinque","Smoithim","Rhaerwar","Leageale","Roining","Untusthon","Kobelom","Ormhintin","Mefar", })
#define HUMAN_NAMES_30 ({ "Rhoudkin","Nuacksay","Straufqua","Thipoltin","Pasis","Kalturrak","Choormgar","Haultet","Kimengis","Cheoughtan","Ostaitur","Peroldser","Rynagesam","Nogarurn","Nyeldight","Raynnaw","Staeghkim","Doarddar",\
    "Leestem","Denendgha","Touvad","Jietir","Oningan","Neyrran","Laelech","Isseldat","Teineurn","Lehinril","Rilithon","Thrikalkin","Honirdan","Thaessad","Claching","Sundang","Kerisash","Tatad","Moaughny","Tirothche","Sidina",\
    "Dulermos","Schaildgha","Rashywar","Sorilkel","Zhebelkel","Chaildight","Zhirdar","Kimightom","Lleenyer","Quaisem","Zhutorold","Chelyehin","Myranim","Peratny","Ildchacer","Snodis","Diadom","Nykimtia","Banustrod","Smeuttor",\
    "Dogarnal","Coultper","Rodaldach","Kimdanild","Keazque","Broostler","Ormtonusk","Issaughlye","Baeklor","Untemaw","Torranold","Radtinryn","Garkinem","Claten","Sidkel","Urnmosenth","Rynrisos","Cheorach","Craivia","Itangtai",\
    "Schikelusk","Vesperunt","Rurayden","Rondnys","Seengdra","Schoenturn","Burasden","Doiwess","Whovesrod","Rothasurn","Stoudbel","Aughskelar","Atitmor","Siormorm","Soutkal","Lasamech","Simoress","Quovan","Choechad","Verrothas",\
    "Ditherenth","Tiormmor","Kooldryn","Sygarskel","Desamar","Zaquegha","Hoorcha","Roanhon","Dracerard","Darormald","Throurdrad","Beuntaugh","Joimen","Inauskath","Zukimar","Thrayrem","Draldlor","Teechny","Dipoltia","Peradess", })
#define HUMAN_NAMES_40 ({ "Zhydansul","Ormpolris","Vorvesage","Raucdan","Ciethque","Neudhat","Niserkel","Smekelgha","Renylor","Goulold","Siror","Emormkal","Nyustnal","Zotassul","Teydche","Hilerdar","Stryestest","Gouvskel","Famorold",\
    "Siplor","Smoertdan","Bosamet","Siendia","Zirodper","Nyslorach","Darinaril","Nyardche","Vettor","Isrisir","Onuntund","Gichia","Garatser","Ightnyler","Sluikrad","Ashdenhat","Myrothves","Meeldcer","Serrothess","Sarisdar","Worashril",\
    "Emtonny","Zhuisim","Isuntang","Belhatis","Strymosash","Etendbur","Chauskwor","Waoldser","Rothtonris","Ackineen","Quoonom","Cromoshat","Schesertas","Levorough","Quietkel","Pehatit","Tolorusk","Whoogen","Zeaturn","Nauskbur","Isransul",\
    "Quadraight","Taiadhon","Teakdyn","Aldnysskel","Cracerust","Quoutusk","Lenyild","Gosis","Hoackshy","Tonrodril","Nobhon","Slotvor","Demosrod","Iriset","Kokinis","Turtanpol","Snoostsay","Troermos","Zuindwor","Tiekton","Thrandyn","Naphina",\
    "Deitor","Urnasough","Quackskel","Ziasas","Echnalkel","Pebanar","Chierine","Sorilale","Toressny","Kaineina","Muagedan","Sauqiss","Ightghadyn","Suessough","Kimessurn","Ustechskel","Tuntor","Crooughsay","Naverar","Echryntur","Boildund",\
    "Vorlertai","Vesingen","Fipheld","Biahpol","Naishdar","Achathaugh","Densamild","Cledanet","Feorrod","Aleosir","Oughundyer","Aughtorqua","Kakalech","Chrarisom","Chruiraw", })

#define HALF_ELF_NAMES_10 ({ "Ilosti","Sisurdru","Isurn","Aellynu","Asty","Illysu","Syadasti","Ailly","Tyirithsu","Heoduello","Tyaerisusuir","Pheoduecal","Iallysum","Aelo","Aeladeu","Airaldeu","Ina","Ailasu","Raelaedru","Adallo",\
    "Reori","Yadue","Phinacal","Haethestisuir","Pheoristi","Aesurdeu","Phainaru","Aisty","Aela","Daraldeu","Eusurstical","Saillysu","Phairithsti","Tyisrideu","Aelaelis","Creolly","Jeulisusuir","Sidue","Eurithnu","Idaisuru",\
    "Iasty","Yada","Laeraldru","Haelinucal","Phiatherian","Aeralsudru","Sisur","Halaeria","Astyllo","Inasti","Riarithru","Rhithe","Hilae","Yarith","Eusty","Raenastin","Arillorap","Alistirin","Iadadeu","Ialaesti","Eoririaru",\
    "Phiadallo","Raidai","Phanallom","Ralasti","Hyali","Eulaera","Tyaerinu","Naelaru","Ryathesti","Illy","Aedairiadeu","Hiada","Illysu","Haelaecal","Eoralstin","Shalonu","Tyaedasuir","Idainurgue","Iananu","Ally","Ilalis","Ailap",\
    "Sinasu","Yanam","Ilonu","Hiastysu","Aeral","Seuli","Aisty","Eulorin","Aethedil","Sidaim","Hyarith","Rithenusuir","Aeri","Ili","Aelallo","Eothe","Aeduestira","Aellyrap","Sadap","Hidueria","Aellyria","Aedairu","Ailaesu","Iathe",\
    "Istyp","Itheriargue","Raedueria","Sairith","Aesurm","Phailosu","Aesrideu","Brailae","Tyithera","Yaralru","Idanu","Phaisty", })
#define HALF_ELF_NAMES_20 ({ "Eunap","Tyeudue","Raesurra","Halaesu","Eodai","Ilodil","Aidai","Tyaisursun","Heusristi","Ryarithllorin","Quaidaillorin","Rilallo","Riallyllodeu","Iasurstin","Tyailillo","Euralsti","Iariria","Raeral",\
    "Neothelis","Zhithe","Sasurphos","Eunariarin","Hadai","Irithdeu","Hada","Histysudeu","Tyidai","Eolillorap","Straela","Phialaeria","Tyaeda","Teoduen","Reostystirin","Irithria","Raesurnudru","Aedacal","Seulaesucal","Idain",\
    "Iaralrin","Illy","Hyali","Iarith","Rialasti","Raidaical","Reulilis","Isri","Riasur","Reolosti","Isri","Ilosuru","Hiada","Hirim","Aelidil","Yaduesu","Pheullynurgue","Aillydru","Ainasu","Alon","Aeral","Caelidil","Aethedeu",\
    "Aellyria","Isrillo","Hithestin","Ilolis","Eorith","Phailallo","Isrisudil","Iadan","Hilo","Tyialo","Hisurria","Phaillysti","Haidailloru","Ryalosun","Iral","Haillyria","Aesrillodil","Aida","Asrinum","Tyinallo","Aeral",\
    "Aenariadru","Zhiri","Iasurnuphos","Ridanuphos","Raesrirgue","Irith","Syasri","Aelasti","Ilae","Tyaestystim","Aidue","Haila","Tyiathelis","Tyalaerap","Airilloru","Tyaedairia","Hasty","Syanarap","Iallynun","Yaliru",\
    "Rilae","Heurithllorgue","Ailarap","Hithesti","Tyidueria","Ainaria","Reoduenuru","Pheusurstira","Seoduep","Asurrap","Eodaidil","Snisri","Reola","Shaeridru","Phaelisu","Eunadil","Irith", })
#define HALF_ELF_NAMES_30 ({ "Tyiasrira","Aeli","Euri","Aeralriargue","Rilisu","Eodarap","Isurra","Yarithsuir","Iri","Astyllo","Isurrian","Aela","Irithllo","Sillyp","Airallodeu","Aelly","Pheusur","Irallophos","Eurithru","Yadaru"\
    ,"Tyastysusuir","Aeralnu","Irith","Idaphos","Ryarith","Eolom","Maerithllorgue","Haithenuphos","Iralnu","Haeduep","Tyisurru","Ryalisu","Aeli","Pharalru","Aestyllocal","Riaral","Tyiarithlis","Tyaithen","Rinasu","Aeral","Eola",\
    "Eusurlis","Eulisu","Iliria","Raestylis","Phaistysti","Phiallydru","Arithnun","Ialaesusuir","Raidasti","Ari","Aidallon","Aistysti","Siada","Phadainun","Isty","Aedanu","Tyiri","Alaesudeu","Airalria","Pheuralnudru","Euririn",\
    "Ili","Allysuir","Arithrap","Phidairgue","Tyaelo","Aerillosuir","Laidasti","Tyeuthe","Eoririadru","Ailallo","Iasrirgue","Phaethe","Tyeoduedeu","Tyila","Deollyllo","Hillyrin","Airallorin","Haduello","Chadaisurgue","Tyallysu",\
    "Ilaesti","Tyadasu","Tyaduedeu","Rilostisuir","Cainasu","Eolastirin","Eonacal","Rallysu","Tyadap","Illy","Philly","Eosrisuir","Teunanup","Tistyra","Ralollo","Ialae","Phaela","Arisun","Aetheriam","Yadallora","Haeralnu",\
    "Aelaergue","Tyiariria","Hiadarap","Iadasup","Thisurrian","Braellysu","Eural","Rilonum","Ilo","Riadaim","Hidai","Philaellorin","Iarithllodil","Sanasuir","Phila","Eonaru", })
#define HALF_ELF_NAMES_40 ({ "Allyriadeu","Phyalocal","Cialisucal","Chriadai","Eoral","Ialadil","Seuralru","Yadaillora","Aeli","Phiadadru","Phiasristi","Aesrisu","Eusurria","Saellynu","Aithem","Ida","Halallo","Jinalis","Aeduenu",\
    "Ala","Sithe","Phiadaira","Ina","Aelasu","Ina","Iri","Heusrira","Euri","Pheoli","Isriria","Schaisrillosuir","Seuthen","Iaduestilis","Ilaem","Inanu","Haedaisu","Ridai","Yaraldru","Seolaedil","Arithllo","Ryadargue","Aliru",\
    "Saellycal","Phaellyriaphos","Eulargue","Chiadue","Tyeulidru","Silly","Hiaduera","Ilostirap","Eoli","Ilacal","Caisrisu","Pheodai","Isur","Aethesu","Ryalirian","Eullyria","Tyaethello","Phisrilis","Tyaerithsu","Euri","Snyadaillo",\
    "Adain","Aedanun","Yalae","Tyeulasu","Pheosrim","Tyistyriadeu","Euliriaphos","Euthe","Aela","Saida","Athe","Syaloru","Asurnu","Phalorin","Eullynudru","Phadanu","Siaral","Tyasririalis","Phaitheria","Idairia","Seolae","Istyrap",\
    "Eori","Eodueriasuir","Aellyru","Naisty","Iduelis","Heural","Aesurnurap","Iathe","Blilly","Yarillo","Heuda","Phaduello","Irithlis","Ila","Tyeuna","Raedueria","Aelollo","Heonanu","Euthen","Aelillodil","Raerideu","Aisurdil","Tyeuli",\
    "Risurdil","Irinu","Haela","Pheuli","Syalollora","Tyastyp","Phaithesum","Aeralnup","Smyasrinu","Yarithsu","Yalaem", })

#define HALF_ORC_NAMES_10 ({ "Echv","Untd","Tonld","Aighty","Vers","Idare","Wart","Etsh","Eissa","Alea","Oima","Ohoni","Iwora","Angq","Sick","Lerl","Toelt","Rothnt","Esule","Thill","Aisse","Gyd","Emt","Etk","Orms","Abano","Swiw","Iunta",\
    "Steuss","Anu","Kant","Oane","Lost","Chald","Lall","Yerq","Theym","Rakn","Yendo","Ber","Rayd","Irrt","Kayth","Undl","Emw","Viend","Clus","Rhech","Iolde","Beln","Aoru","Nall","Radrr","Eema","Eilda","Emt","Seysh","Uemu","Ausku","Orothu",\
    "Etina","Kieck","Whool","Uentha","Aose","Soond","Lolk","Kimg","Anyu","Urothi","Oldrt","Atai","Oina","Der","Aghae","Ikina","Mert","Iart","Achs","Itany","Adrae","Dill","Oelme","Sat","Upolu","Chaegh","Ess","Uhate","Poll","Arm","Etth",\
    "Ukina","Clik","Oorma","Kel","Estk","Enc","Orml","Rakt","Serld","Ashyi","Bayh","Eraye","Blin","Yenthi","Gys","Radck","Cliert","Tees","Eaugha","Loun","Scheik","Irl","Uity","Essd","Ydani","Iundy","Craird","Oinae", })
#define HALF_ORC_NAMES_20 ({ "Awh","Kaed","Lead","Dor","Phil","Ethery","Warc","Houl","Rhoet","Otaia","Ustn","Tinl","Emnd","Urnt","Roch","Schayn","Aormo","Otoro","Yernd","Ydray","Ikino","Icero","Ybeli","Inglt","Brunt","Ienthi","Ormd",\
    "Yburu","Rieph","Itss","Hiel","Uange","Haez","Chad","Ardf","Aildi","Crorr","Crib","Oisy","Soen","Ychae","Sleez","Lloird","Umnn","Idely","Elyea","Reyt","Amose","Sayl","Zaygh","Yunta","Emb","Yeag","Swoil","Tasp","Ueche","Elmm",\
    "Ess","Eawi","Owori","Ornn","Throgh","Aradu","Burnt","Yawu","Ahona","Rotht","Aenda","Endll","Guk","Ast","Asnd","Dob","Swas","Adany","Ovory","Ormss","Elory","Tanph","Noed","Abanu","Quenn","Ackb","Shoph","Aesto","Ourny","Sheuph",\
    "Chook","Baind","Roith","Creep","Sayh","Irana","Ror","Koorr","Ceyt","Biam","Drit","Danlt","Vesn","Emst","Oaughe","Usulo","Irani","Ages","Luil","Ialde","Rothsh","Strayq","Urna","Engn","Tongh","Toum","Urada","Itheri","Nalt","Oildi","Bial","Aqua", })
#define HALF_ORC_NAMES_30 ({ "Noc","Isn","Eena","Tonc","Adara","Ielma","Pien","Niah","Isnn","Cleq","Zoenn","Goun","Vorb","Uaty","Thuph","Searr","Ubanu","Leld","Meem","Wheyl","Lorph","Obura","Echt","Ashr","Oasa","Vorl","Norr","Sayrr",\
    "Tuph","Honm","Uvora","Iathe","Rail","Saelt","Lyeb","Orms","Idynu","Oany","Amosa","Keuck","Bant","Emk","Oathy","Iwaro","Polrr","Clairt","Brom","Swoeck","Shaim","Kuld","Nys","Strit","Umnt","Inez","Leur","Sith","Rillt","Serk",\
    "Deep","Aldq","Onya","Itana","Elml","Lluv","Ackll","Shoirt","Inan","Yerl","Asame","Delw","Worrt","Umi","Ads","Denl","Essn","Hatg","Yurny","Uanu","Uire","Wargh","Oldck","Zill","Turh","Sniac","Ebure","Obure","Aissi","Quer",\
    "Aome","Queb","Aingy","Achck","Thrund","Lor","Siess","Croud","Boor","Tiass","Slein","Ches","Thead","Uome","Emn","Ildy","Ial","Ytasi","Jol","Chef","Drag","Boold","Achk","Schond","Atia","Evero","Nysph","Sall","Toirr","Aldl","Belt", })
#define HALF_ORC_NAMES_40 ({ "Oml","Oaldi","Strud","Zeyg","Ymosi","Perf","Enthnn","Sull","Niam","Rodz","Arg","Vernt","Emn","Whien","Lok","Ahino","Vors","Ainai","Uryni","Aso","Imnn","Sleig","Yarde","Rang","Kels","Veit","Shev"\
    ,"Eathi","Imrr","Ealeo","Streug","Tinc","Heis","Estnt","Ting","Uskl","Lord","Ormb","Awll","Ighau","Geil","Iashe","Udyna","Achz","Zein","Schoos","Essb","Edenu","Rear","Tem","Cull","Undt","Aunta","Lliarr","Geek","Briard",\
    "Ichai","Chal","Hatd","Naiss","Osuly","Oenthy","Rothnn","Iloro","Kimy","Iasho","Oaughy","Thyd","Erothu","Oimu","Nalk","Morn","Orss","Bray","Oinao","Croet","Taid","Dys","Echk","Thooss","Oghae","Epery","Hiah","Arll","Wieh",\
    "Omk","Slof","Biah","Samnd","Oumo","Arth","Rierr","Igary","Naert","Dried","Vorll","Burnd","Darnn","Winn","Orisy","Ighth","Jonn","Soop","Beirt","Wup","Swash","Smeerr","Ukala","Uiao","Alem","Lolt","Ime","Askelo","Honnt","Igaro","Radk","Irth","Urnt","Verq", })
