// Great hall of the tower
// Thorn@ShadowGate
// 001027
// Solaren's Player House
// solaren5.c
// modified to become a mage guild tower ala Sherlock & Stefano by *Styx* 4/21/03

#include <std.h>

inherit VAULT;

void create() {
  ::create();
   set_name("Assembly Hall");
   set_terrain(STONE_BUILDING);
   set_travel(PAVED_ROAD);
  set_property("light", 2);
  set_property("indoors", 1);
  set_short("%^BOLD%^Assembly hall of the tower%^RESET%^");
  set_long("%^BOLD%^Assembly hall of the tower%^RESET%^\n"
"You are in the immense assembly hall of the tower.  A %^MAGENTA%^mosaic "
"crest %^RESET%^takes up the entire floor.  On a wall, engraved in large "
"letters in the stone, in all languages, is written the charge.  The far "
"end of the floor is raised in a semi circle around the base of the tower, "
"forming a podium.  Upon the raised part are three large chairs and several "
"smaller chairs, each with a side table.  At the end of the room, at the "
"centre of the raised floor is a large fireplace and a doorway that leads "
"north to a hall.  Above "
"the northern doorway is displayed an %^CYAN%^address to the Guild%^RESET%^."
"  A large sign is on the eastern wall, surrounded by %^RED%^fine tapestries"
"%^RESET%^.  Smaller entrances lead to the south and the east."
   );

/*
@THORN
%^BOLD%^Great hall of the tower%^RESET%^
Great double doors onto a grand hall, filled with several tables that
might seat up to 25 guests in comfort.  Along the northern wall is a
large fireplace. which serves to heat the Hall in both summer and in
winter and serves as the focal point for a comfortable sitting area. 
Lush tapestries hang along the walls of the room.  Double sets of doors
lead out of the hall to the north on either side of the fireplace, and
there are smaller openings to the east and the south.
THORN
  );
*/
  set_listen("default", "The room is filled with the murmur of private conversations.");
  set_smell("default", "The room is kept clean and the smell of the polish dominates.");
  set_items(([
    "tapestries" : "%^RED%^These wall hangings depict battles of the past and flying beasts of all sorts.",
    "fireplace" : "This fireplace serves as the focal point for a comfortable sitting area as well as for heating.",
    "crest" : "%^MAGENTA%^The crest takes the form of an orb containing a scroll "
	"lying across an open spell book.  Again, like outside, the words around "
	"the edges are blurred though parts can be made out here:\n  '%^BOLD%^The "
	"greatest part of the weave has yet to be discovered, seek this knowledge "
	"always yet know that only by ..... can this knowledge be found.%^RESET%^'",
    "charge" : "  The Guild is the sum of the knowledge generated by its members "
	"past and present.  In your research and in your teachings, strive to "
	"further the understanding of magic within the realm and so increase "
	"the knowledge of the Guild.  Where the Guild allows you to benefit, "
	"sell your knowledge to, and only to, the Guild itself.\n\n  Uphold the "
	"dignity of the profession of mage, and do not allow others to cheapen "
	"the worth of your talents, knowledge and abilities.  Never act in such "
	"a way as to do so yourself.  Where the Weave is threatened or where "
	"the interests of the Guild are compromised, be prepared to stand as "
	"one to meet such a threat.  Be prepared to act to further the interests "
	"of the Guild as an institution of magic within the realm whether this "
	"be through financial, material or other means.",
    "address" : "You see written in the stone:  '%^CYAN%^When you enter these "
	"doors you do so with the hand of history on your shoulder.  To enter "
	"here places you at the forefront of wizardry in these realms, in all "
	"its forms.  Beyond these doors lies an institution that will stand "
	"the test of time.  Do it proud and make it so.%^RESET%^'",
    "chairs" : "You see the chairs set out on the semi-circular raised portion of the floor.  Each of the larger chairs is flanked by two to three smaller chairs.",
    "podium" : "The podium is raised three foot from the floor with steps leading up to it.  It gives a clear impression that those who inhabit the tower address the floor from there.",

  ]));
  set_exits(([
      "north" : "/d/player_houses/solaren/solaren8",
      "south" : "/d/player_houses/solaren/solaren6",
      "east" : "/d/player_houses/solaren/solaren7",
      "exit" : "/d/player_houses/solaren/solaren4",
  ]));
  set_door("double doors","/d/player_houses/solaren/solaren4","exit");
  set_door_description("double doors", "%^BLUE%^The midnight blue oak doors look solid.  The lock looks disabled.");
}

void reset(){
  ::reset();  
}
