//for Lothwaite signet rings.  Circe 6/18/04

#define HEADER "#include <std.h>\ninherit ARMOUR;\n\nstring symbol1;\nstring symbol2;\nstring weapon1;\nstring weapon2;\nstring initial1;\nstring initial2;\nstring background;\nvoid create(){\n\t::create();\n"
#define NAME "\tset_name(\"signet ring\");\n"
#define ID "\tset_id(({\"ring\",\"signet ring\",\"signet\"}));\n"
#define SHORT "\tset_short(\"signet ring\");\n"
#define MYSYMBOL1(x) "\tsymbol1 = \""+x+"\";\n"
#define MYWEAPON1(x) "\tweapon1 = \""+x+"\";\n"
#define MYINITIAL1(x) "\tinitial1 = \""+x+"\";\n"
#define MYSYMBOL2(x) "\tsymbol2 = \""+x+"\";\n"
#define MYWEAPON2(x) "\tweapon2 = \""+x+"\";\n"
#define MYINITIAL2(x) "\tinitial2 = \""+x+"\";\n"
#define MYBACK(x) "\tbackground = \""+x+"\";\n"
#define LONG "\tset_long(\"This finely crafted signet ring is made of high quality %^BOLD%^white gold%^RESET%^.  It is a rather thick ring with a round, flat top that features \"+(string)TO->query_seal()+\"\");\n"
#define LORE "\set_lore(\"This signet ring was made by Edric, the firbolg jeweler in the village of Lothwaite.  Its symbols bear meaning for one person and refer to him or her alone.\");\n"
#define LOREDIFF "set_property(\"lore difficulty\",12);\n"
#define WEIGHT "\tset_weight(1);\n"
#define VALUE "\tset_value(750);\n"
#define AC "\tset_ac(0);\n"
#define LIMBS "\tset_limbs(({\"right hand\"}));\n"
#define TYPE "\tset_type(\"ring\");\n"
#define CLOSE "}\n"
#define WF(x) write_file(FILE,x)
#define SYM "int query_symbol(){ return \"\"+symbol1+\"\";}\n"
#define WEA "int query_weapon(){ return \"\"+weapon1+\"\";}\n"
#define INI "int query_initial(){ return \"\"+initial1+\"\";}\n"
#define SYM2 "int query_symbol2(){ return \"\"+symbol2+\"\";}\n"
#define WEA2 "int query_weapon2(){ return \"\"+weapon2+\"\";}\n"
#define INI2 "int query_initial2(){ return \"\"+initial2+\"\";}\n"
#define BAC "int query_background(){ return \"\"+background+\"\";}\n"
#define SEAL "int query_is_seal_device(){ return 1;}\n"
#define MYSEAL1 "int query_seal(){ return \"a backdrop of \"+background+\".  On top of the background is the finely detailed image of \"+weapon1+\".  In the foreground, drawing your attention, is the raised carving of \"+symbol1+\".\"; }\n"
#define MYSEAL2 "int query_seal(){ return \"a backdrop of \"+background+\".  On top of the background is the finely detailed image of \"+symbol1+\", accented by \"+initial1+\".\"; }\n"
#define MYSEAL3 "int query_seal(){ return \"a backdrop of \"+background+\".  On top of the background is the finely detailed image of \"+weapon1+\", accented by \"+initial1+\".\"; }\n"
#define MYSEAL4 "int query_seal(){ return \"a backdrop of \"+background+\".  On top of the background is the finely detailed image of \"+symbol1+\" beside an intricate depiction of \"+symbol2+\".\"; }\n"
#define MYSEAL5 "int query_seal(){ return \"a backdrop of \"+background+\".  On top of the background is the finely detailed image of \"+weapon1+\" beside an intricate depiction of \"+weapon2+\".\"; }\n"
#define MYSEAL6 "int query_seal(){ return \"a backdrop of \"+background+\".  On top of the background is the finely detailed image of \"+initial1+\" interlocked with the intricate depiction of \"+initial2+\".\"; }\n"
#define MYSEAL7 "int query_seal(){ return \"a backdrop of \"+background+\".  On top of the background is the finely detailed image of \"+symbol1+\".\"; }\n"
#define MYSEAL8 "int query_seal(){ return \"a backdrop of \"+background+\".  On top of the background is the finely detailed image of \"+weapon1+\".\"; }\n"
#define MYSEAL9 "int query_seal(){ return \"a backdrop of \"+background+\".  On top of the background is the finely detailed image of \"+initial1+\".\"; }\n"
#define MYSEAL10 "int query_seal(){ return \"a finely detailed image of \"+weapon1+\".  In the foreground, drawing your attention, is the raised carving of \"+symbol1+\".\"; }\n"
#define MYSEAL11 "int query_seal(){ return \"a finely detailed image of \"+symbol1+\", accented by \"+initial1+\".\"; }\n"
#define MYSEAL12 "int query_seal(){ return \"a finely detailed image of \"+weapon1+\", accented by \"+initial1+\".\"; }\n"
#define MYSEAL13 "int query_seal(){ return \"a finely detailed image of \"+symbol1+\" beside an intricate depiction of \"+symbol2+\".\"; }\n"
#define MYSEAL14 "int query_seal(){ return \"a finely detailed image of \"+weapon1+\" beside an intricate depiction of \"+weapon2+\".\"; }\n"
#define MYSEAL15 "int query_seal(){ return \"a finely detailed image of \"+initial1+\" interlocked with the intricate depiction of \"+initial2+\".\"; }\n"
#define MYSEAL16 "int query_seal(){ return \"a finely detailed image of \"+symbol1+\".\"; }\n"
#define MYSEAL17 "int query_seal(){ return \"a finely detailed image of \"+weapon1+\".\"; }\n"
#define MYSEAL18 "int query_seal(){ return \"a finely detailed image of \"+initial1+\".\"; }\n"