#define GY_ROAD "/realms/saide/graveyard/gyroad_inh"
#define GY_ROOMS "/realms/saide/graveyard/"
#define GRAVEYARD "/realms/saide/graveyard/graveyd_inh"
#define BH_ROOMS "/d/deku/hhouse/"
#define HH_ROOMS "/d/deku/hhouse/"
#define DEKU_TR "/d/deku/inherits/treasure"
#define CR_ROOMS "/d/deku/crater/rooms/"