/* Standard Object Properties */

#define WEIGHT                "object_weight"
#define VALUE                 "object_volume"
#define DIMENSIONS            "object_dimensions"
#define NO_GET                "object_no_get"
#define NO_DROP               "object_no_drop"
#define NO_PUT                "object_no_put"
#define NO_GIVE               "object_no_give"
#define WET                   "object_wet"
#define CONDITION             "object_condition"
#define IS_PLAYER             "object_is_player"
#define IS_MONSTER            "object_is_monster"
#define IS_ROOM               "object_is_room"
#define INVIS                 "object_invis"
#define SEE_INVIS             "object_see_invis"
