#define TEC "/d/atoyatl/tecqumin/"
#define CORRIDORBASE "/d/atoyatl/tecqumin/base_files/corridor_base.c"
#define GARDENBASE "/d/atoyatl/tecqumin/base_files/garden_base.c"
#define TECBASE "/d/atoyatl/tecqumin/base_files/"
#define C_ROAD_BASE "/d/atoyatl/tecqumin/base_files/clear_road_base.c"
#define ENERGY_SOURCE "/d/atoyatl/tecqumin/obj/energy_source_base.c"
#define GUARD_STEP "/d/atoyatl/tecqumin/rooms/guardstep.c"
#define MOB "/d/atoyatl/tecqumin/mons/"
#define OBJ "/d/atoyatl/tecqumin/obj/"
#define ROOMS "/d/atoyatl/tecqumin/rooms/"
#define STEP_LOW "/d/atoyatl/tecqumin/rooms/step_low.c"
#define STEP_MID "/d/atoyatl/tecqumin/rooms/step_mid.c"
#define STEP_HIGH "/d/atoyatl/tecqumin/rooms/step_high.c"
#define ZIG "/d/atoyatl/tecqumin/rooms/zig.c"
#define ZIG_INT_BASE "/d/atoyatl/tecqumin/base_files/zig_int_base.c"
#define ZIG_LOW "/d/atoyatl/tecqumin/rooms/zig_low.c"
#define ZIG_MID "/d/atoyatl/tecqumin/rooms/zig_mid.c"
#define ZIG_HIGH "/d/atoyatl/tecqumin/rooms/zig_high.c"
#define ZIG_HIGHEST "/d/atoyatl/tecqumin/rooms/zig_highest.c"
#define ZIG_FRONT_LOW "/d/atoyatl/tecqumin/rooms/zig_front_low.c"
#define ZIG_FRONT_MID "/d/atoyatl/tecqumin/rooms/zig_front_mid.c"
#define CANYON_RIVERBANK "/d/atoyatl/tecqumin/base_files/canyon_riverbank_base.c"
#define CANYON_PATH "/d/atoyatl/tecqumin/base_files/canyon_path_base.c"
#define KAYAK "/d/atoyatl/tecqumin/base_files/kayak.c"
#define MAZE "/d/atoyatl/tecqumin/base_files/maze_base.c"
#define MAZEROOMS "/d/atoyatl/tecqumin/maze/"
#define PHASE_MON "/d/atoyatl/tecqumin/mons/phase_mon.c"
#define HUNT_MON "/d/atoyatl/tecqumin/mons/hunt_mon.c"
#define LOW_MAZE "/d/atoyatl/tecqumin/rooms/low_maze"
#define CULT_ITEM "/d/atoyatl/tecqumin/obj/cultural_items.c"
#define SCANNER "/d/atoyatl/obs/far_scanner2.c"
#define DESTROOM "/d/atoyatl/tecqumin/rooms/destination_room.c"
#define GHOST_PRIEST "/d/atoyatl/tecqumin/mons/ghost_priest.c"
#define GHOST_WARRIOR "/d/atoyatl/tecqumin/mons/ghost_warrior.c"
#define CORRIDOR "/d/atoyatl/tecqumin/rooms/corridor.c"
#define TUNBASE "/d/atoyatl/tecqumin/base_files/tunbase.c"
#define BRIDGEBASE "/d/atoyatl/tecqumin/base_files/bridge_base.c"
#define CANALBANK_BASE "/d/atoyatl/tecqumin/base_files/canalbank_base.c"
#define JCITY "/d/atoyatl/tecqumin/city/"
#define CITY_ROOM "/d/atoyatl/tecqumin/city/rooms/"
#define CITY_JUNG "/d/atoyatl/tecqumin/base_files/city_jung_base.c"
#define GRAND_HUT_BASE "/d/atoyatl/tecqumin/base_files/grand_hut_base.c"
#define GRAND_RUIN_BASE "/d/atoyatl/tecqumin/base_files/grand_ruin_base.c"
#define HUT_BASE "/d/atoyatl/tecqumin/base_files/hut_base.c"
#define HUT_INT_BASE "/d/atoyatl/tecqumin/base_files/hut_interior_base.c"
#define JUNG "/d/atoyatl/tecqumin/jungle/"
#define JUNG_ROOM "/d/atoyatl/tecqumin/jungle/rooms/"
#define JUNG_ROOM1 "/d/atoyatl/tecqumin/junglea/rooms/"
#define JUNG_ROOM2 "/d/atoyatl/tecqumin/jungleb/rooms/"
#define JUNG_ROOM3 "/d/atoyatl/tecqumin/junglec/rooms/"
#define JUNG_ROOM4 "/d/atoyatl/tecqumin/jungled/rooms/"
#define JUNG_ROOM5 "/d/atoyatl/tecqumin/junglee/rooms/"
#define JUNG_ROOM6 "/d/atoyatl/tecqumin/junglef/rooms/"
#define JUNG_ROOM7 "/d/atoyatl/tecqumin/jungleg/rooms/"
#define JUNG_ROOM8 "/d/atoyatl/tecqumin/jungleh/rooms/"
#define JUNG_ROOM9 "/d/atoyatl/tecqumin/junglei/rooms/"
#define JUNG_ROOM10 "/d/atoyatl/tecqumin/junglej/rooms/"
#define JUNG_ROOM11 "/d/atoyatl/tecqumin/junglek/rooms/"
#define JUNG_ROOM12 "/d/atoyatl/tecqumin/junglel/rooms/"
#define J_ROOM "/d/atoyatl/tecqumin/base_files/jung_base.c"
#define J_MAZE "/d/atoyatl/tecqumin/base_files/maze_base.c"
#define PATH_BASE "/d/atoyatl/tecqumin/rooms/path_base.c"
#define R_ROAD_BASE "/d/atoyatl/tecqumin/base_files/ragged_road_base.c"
#define RUIN_BASE "/d/atoyatl/tecqumin/base_files/ruin_base.c"
#define TEST "/d/atoyatl/tecqumin/test/"
#define TECSTORE "/d/atoyatl/tecqumin/rooms/storage/tec_storage.c"
#define TECVOID "/d/atoyatl/tecqumin/void/"
#define BUILDER "/d/atoyatl/maze_d"
#define WEMIC "/d/atoyatl/wemic/rooms/"
#define TREEHOUSE "/d/atoyatl/tecqumin/treehouse"
#define TABAXROOM "/d/atoyatl/tecqumin/tabaxi/rooms/"
#define TABAXOBJ "/d/atoyatl/tecqumin/tabaxi/obj/"
#define TABAXBASE "/d/atoyatl/tecqumin/tabaxi/base_files/"
#define SEAL_PICS "/d/atoyatl/tecqumin/seal_pics.h"
#define MOB_MODIFIER_D "/realms/lujke/daemon/mob_modifier_d.c"
#define LOW_FIELD 1
#define MAIN_FIELD 2
#define HIGH_FIELD 3
#define NO_TARGET 0
#define OIL 1
#define ROCKS 2
#define WATERYLIQUID 3
#define SAND 4
#define LOG "/d/atoyatl/tecqumin/log/"
#define CAMOUFLAGE "%^GREEN%^c%^ORANGE%^a%^GREEN%^mou%^BOLD%^%^GREEN%^f%^RESET%^%^GREEN%^l%^ORANGE%^a"\
                   +"%^GREEN%^ge%^RESET%^"
#define CAMOUFLAGED "%^GREEN%^c%^ORANGE%^a%^GREEN%^mou%^BOLD%^%^GREEN%^f%^RESET%^%^GREEN%^l%^ORANGE%^"\
                   +"a%^GREEN%^g%^BOLD%^%^GREEN%^e%^RESET%^%^GREEN%^d%^RESET%^"
#define CAMOUFLAGING "%^GREEN%^c%^ORANGE%^a%^GREEN%^mou%^BOLD%^%^GREEN%^f%^RESET%^%^GREEN%^"\
                   +"l%^ORANGE%^a%^GREEN%^g%^BOLD%^%^GREEN%^i%^RESET%^%^GREEN%^ng%^RESET%^"
#define HEXER_D "/d/atoyatl/hexer_d.c"
#define RAM 0
#define WAIT 1
#define SWING 2
#define LADDER 3
#define STOPPED 4
#define ARCHERY 5
#define WALK_IN 6
#define REGROUPING 7
#define CLIMB 8
#define RIVER "/d/atoyatl/tecqumin/rooms/river.c"
#define SCRAMBLE 0
#define SQUEEZE 2
#define EAST 1
#define WEST 2
#define STATIONARY -1
#define ASCENDING 3
#define DESCENDING 4

#define DAY 24000   // 20 seconds in one minute
                    // 60 minutes in one hour
                    // 20 hours in one day
#define MAZE_D "d/atoyatl/maze_d"
#define MELEE 1
#define RANGED 2
#define TARGETSPELL 3
#define AREASPELL 4
