#define N "north"
#define S "south"
#define E "east"
#define W "west"
#define NE "northeast"
#define NW "northwest"
#define SE "southeast"
#define SW "southwest"
#define U "up"
#define D "down"
#define EA "enter armory"
#define EW "enter weaponry"
#define OUT "out"
#define EC "enter coffee shop"
#define ER "enter restaurant"
