//Ryzan and Aunuit's House
//Coded by ~Circe~ 7/29/13

#include <std.h>
#include "aunuit.h"
inherit AUNUIT;

void create(){
   ::create();
   set_property("fill waterskin",1);
   set_name("Enchanted Grotto");
   set_short("%^BOLD%^%^BLACK%^Enchanted Grotto%^RESET%^");
   set_long("%^BOLD%^%^BLACK%^D%^CYAN%^a%^BLACK%^mp stone surrounds "
      "you here, %^CYAN%^flu%^GREEN%^o%^CYAN%^r%^RESET%^%^CYAN%^e"
      "%^BOLD%^%^CYAN%^sc%^GREEN%^e%^CYAN%^nt l%^WHITE%^i%^CYAN%^"
      "ch%^GREEN%^e%^CYAN%^n %^BLACK%^clinging to the walls and "
      "ceiling in thick patches that lend the area minimal "
      "%^WHITE%^illumination%^BLACK%^. Massive stalactites hang "
      "from the soaring ceiling, %^RESET%^%^CYAN%^mo%^BOLD%^"
      "%^CYAN%^i%^RESET%^%^CYAN%^st%^GREEN%^u%^CYAN%^re %^BOLD%^"
      "%^BLACK%^slowly gathering to drip into the %^RESET%^"
      "%^CYAN%^w%^BOLD%^%^BLUE%^a%^RESET%^%^CYAN%^t%^BOLD%^"
      "%^CYAN%^e%^RESET%^%^CYAN%^r %^BOLD%^%^BLACK%^below. The "
      "cavern houses two %^CYAN%^pools %^BLACK%^separated by "
      "a precipice. The larger of the two is located on the "
      "lower plain and is quite expansive. %^WHITE%^Cr%^CYAN%^y"
      "%^WHITE%^stal cl%^CYAN%^e%^RESET%^%^CYAN%^a%^BOLD%^"
      "%^WHITE%^r wat%^CYAN%^e%^WHITE%^r %^BLACK%^resides within, "
      "revealing a deep rocky bottom lit by %^CYAN%^flu%^GREEN%^o"
      "%^CYAN%^r%^RESET%^%^CYAN%^e%^BOLD%^%^CYAN%^sc%^GREEN%^e"
      "%^CYAN%^nt aqu%^GREEN%^a%^CYAN%^t%^RESET%^%^CYAN%^i%^BOLD"
      "%^%^CYAN%^c pl%^RESET%^%^GREEN%^a%^BOLD%^%^CYAN%^nt "
      "l%^RESET%^%^CYAN%^i%^BOLD%^%^CYAN%^fe%^BLACK%^. Gl"
      "%^WHITE%^i%^BLACK%^tt%^RESET%^e%^BOLD%^%^BLACK%^r%^WHITE%^"
      "i%^BLACK%^ng g%^MAGENTA%^e%^BLACK%^mst%^CYAN%^o%^BLACK%^n"
      "%^WHITE%^e%^BLACK%^s dot the %^RESET%^%^ORANGE%^rough "
      "r%^WHITE%^o%^ORANGE%^cks%^BOLD%^%^BLACK%^. Along the "
      "northeastern corner of the wall a set of stone steps "
      "ascend to the upper tier of the %^RESET%^%^CYAN%^grotto"
      "%^BOLD%^%^BLACK%^. %^RESET%^Steam %^BOLD%^%^BLACK%^rises "
      "from the %^CYAN%^smaller pool%^BLACK%^. Its location and "
      "size makes for a more intimate, %^RESET%^%^RED%^rom"
      "%^MAGENTA%^a%^RED%^ntic atm%^MAGENTA%^o%^RED%^sph%^BOLD%^"
      "%^RED%^e%^RESET%^%^RED%^re%^BOLD%^%^BLACK%^. Suspended "
      "between a pair of natural columns near the heated pool "
      "is a sturdy sp%^WHITE%^i%^BLACK%^d%^RED%^e%^BLACK%^r"
      "%^RESET%^s%^BOLD%^%^WHITE%^i%^RESET%^lk h%^BOLD%^%^RED%^a"
      "%^RESET%^mmo%^BOLD%^%^WHITE%^c%^RESET%^k%^BOLD%^%^BLACK%^. "
      "Both pools appear to be fed by an %^RESET%^%^CYAN%^"
      "underground stream%^BOLD%^%^BLACK%^, the %^CYAN%^w%^RESET%^"
      "%^CYAN%^a%^BOLD%^%^CYAN%^ter fl%^RESET%^%^CYAN%^o%^BOLD%^"
      "%^CYAN%^w%^BLUE%^i%^CYAN%^ng %^BLACK%^through unseen "
      "cr%^RESET%^e%^BOLD%^%^BLACK%^vices, resulting in a lazy "
      "current. Around the pools the stalagmites have been "
      "reshaped into statuary and seating. %^RESET%^Adamantium "
      "braziers %^BOLD%^%^BLACK%^are suspended from the "
      "stalactites hanging from the grotto's ceiling, %^RESET%^"
      "%^ORANGE%^fr%^RED%^a%^ORANGE%^gr%^MAGENTA%^a%^ORANGE%^nt "
      "ch%^BOLD%^%^RED%^i%^RESET%^%^ORANGE%^ps %^BOLD%^%^BLACK%^"
      "b%^RED%^u%^BLACK%^rning within.%^RESET%^\n");
   set_smell("default","%^RESET%^%^CYAN%^The braziers release an intoxicating fragrance.%^RESET%^");
   set_listen("default","%^BOLD%^%^BLACK%^The sound of running water echoes off the cavern walls.%^RESET%^");
   set_items(([
      ({"braziers","brazier"}) : "%^BOLD%^%^BLACK%^Diamond-shaped "
         "%^RESET%^adamatium braziers %^BOLD%^%^BLACK%^hang from "
         "chains anchored to the stalactites. Pale %^RESET%^sm%^BOLD%^"
         "%^WHITE%^o%^RESET%^ke %^BOLD%^%^BLACK%^spills from tiny "
         "perforations made in the metal. The scent released from "
         "the braziers is %^RESET%^%^MAGENTA%^int%^RED%^o%^MAGENTA%^"
         "xicating%^BOLD%^%^BLACK%^.%^RESET%^",
      ({"stalactites","stalactite","ceiling"}) : "%^BOLD%^%^BLACK%^Thick, "
         "jagged stalactites hang from the cavernous ceiling. They are "
         "coated in %^WHITE%^wh%^RESET%^i%^BOLD%^%^WHITE%^te c%^BLACK%^a"
         "%^WHITE%^lcium %^BLACK%^deposits and %^RESET%^%^CYAN%^"
         "precipitation%^BOLD%^%^BLACK%^. Diamond-shaped %^RESET%^"
         "adamantium braziers %^BOLD%^%^BLACK%^hang from many of the "
         "stalactites.%^RESET%^",
      ({"stalagmites","stalagmite","bench","benches","statues","statue"}) :
         "%^BOLD%^%^BLACK%^Sizable stalagmites emerge from the "
         "grotto's stone floor. Many have been reshaped into seating and "
         "statuary by an artist with a keen eye for detail. Both the "
         "benches and statues are wreathed in shad%^RESET%^%^BLUE%^o"
         "%^BOLD%^%^BLACK%^wy t%^RESET%^e%^BOLD%^%^BLACK%^ndrils. "
         "Graceful and lithe each of the effigies is a life-size "
         "depiction of a nude, dancing elf. Their specific lineages "
         "indiscernible, there are %^RESET%^%^MAGENTA%^females "
         "%^BOLD%^%^BLACK%^as well as %^RESET%^%^RED%^males %^BOLD%^"
         "%^BLACK%^present, and all are %^CYAN%^br%^RESET%^%^CYAN%^"
         "ea%^BOLD%^%^CYAN%^thtak%^WHITE%^i%^CYAN%^ng %^BLACK%^to behold.%^RESET%^",
      ({"hammock","columns","column"}) : "%^BOLD%^%^BLACK%^These two "
         "natural columns reach to the ceiling of the grotto. Situated "
         "near the hot spring they have a sp%^WHITE%^i%^BLACK%^d%^RED%^"
         "e%^BLACK%^r%^RESET%^s%^BOLD%^%^WHITE%^i%^RESET%^lk h%^BOLD%^"
         "%^RED%^a%^RESET%^mmo%^BOLD%^%^WHITE%^c%^RESET%^k %^BOLD%^"
         "%^BLACK%^stretched between them. The %^WHITE%^w%^RESET%^e"
         "%^BOLD%^%^WHITE%^b %^BLACK%^pattern of the %^WHITE%^s%^RED%^"
         "i%^WHITE%^lk %^BLACK%^is as intricate and myriad in design "
         "as one woven by an actual sp%^RED%^i%^BLACK%^der. A soft "
         "%^WHITE%^glow %^BLACK%^surrounds the hammock itself as "
         "%^WHITE%^l%^RESET%^i%^BOLD%^%^WHITE%^ght tr%^RESET%^a"
         "%^BOLD%^%^WHITE%^ils %^BOLD%^%^BLACK%^course through the "
         "s%^WHITE%^i%^BLACK%^l%^CYAN%^v%^RESET%^e%^BOLD%^%^BLACK%^ry "
         "material, providing a stunning %^WHITE%^highlighting "
         "%^BLACK%^effect.%^RESET%^",
      "pool 1" : "%^BOLD%^%^BLACK%^This large %^BOLD%^%^WHITE%^cr"
         "%^CYAN%^y%^WHITE%^stall%^RESET%^%^CYAN%^i%^BOLD%^%^WHITE%^ne "
         "p%^CYAN%^o%^RESET%^%^CYAN%^o%^BOLD%^%^WHITE%^l %^BLACK%^"
         "occupies a majority of the lower level of the grotto. "
         "Smooth long rocks border the pool and are a perfect place "
         "for lounging. A few %^RESET%^%^ORANGE%^thatch mats %^BOLD%^"
         "%^BLACK%^have been lain out for just that purpose. "
         "Illuminated by %^CYAN%^flu%^GREEN%^o%^CYAN%^r%^RESET%^"
         "%^CYAN%^e%^BOLD%^%^CYAN%^sc%^GREEN%^e%^CYAN%^nt aqu"
         "%^GREEN%^a%^CYAN%^t%^RESET%^%^CYAN%^i%^BOLD%^%^CYAN%^c "
         "pl%^RESET%^%^GREEN%^a%^BOLD%^%^CYAN%^nt l%^RESET%^%^CYAN%^i"
         "%^BOLD%^%^CYAN%^fe%^BLACK%^ you can see straight through "
         "the water to the bottom, which is quite deep toward the "
         "middle. The rocky floor is studded with gl%^WHITE%^i"
         "%^BLACK%^tt%^RESET%^e%^BOLD%^%^BLACK%^ring %^MAGENTA%^g"
         "%^RESET%^%^MAGENTA%^e%^BOLD%^%^MAGENTA%^m%^BLACK%^st"
         "%^RESET%^o%^BOLD%^%^BLACK%^ne deposits. A very faint "
         "current causes the water to circle lazily.%^RESET%^",
      "pool 2" : "%^BOLD%^%^BLACK%^Directly north of the %^CYAN%^"
         "larger pool %^BLACK%^a rock face rises about twenty "
         "feet off the ground. A set of stairs has been carved "
         "from the side of the small cliff and winds around it. "
         "They lead to a smaller %^RESET%^%^RED%^hot spring "
         "%^BOLD%^%^BLACK%^that exists at the top. %^RESET%^Steam"
         "%^BOLD%^%^BLACK%^ rises off the surface of the %^CYAN%^"
         "clear water%^BLACK%^, which circles lazily. Due to the "
         "fact that it is much shallower than the pool below, and "
         "truly only meant for lounging, a circular bench has been "
         "carved from the interior perimeter. The %^GREEN%^pl%^CYAN%^"
         "a%^GREEN%^nt l%^RESET%^%^CYAN%^i%^BOLD%^%^GREEN%^fe %^BLACK%^"
         "has also been cleared away and the floor leveled. To the east "
         "of the pool are two natural columns that extend from the top "
         "of the peak of the steep hill to the ceiling. Stretched "
         "between them is a sturdy sp%^RED%^i%^BLACK%^d%^WHITE%^er"
         "%^RESET%^s%^BOLD%^%^WHITE%^i%^RESET%^lk h%^BOLD%^%^RED%^a"
         "%^RESET%^mmo%^BOLD%^%^WHITE%^c%^RESET%^k%^BOLD%^%^BLACK%^.%^RESET%^",
      ({"floor","ground"}) : "%^BOLD%^%^BLACK%^The floor is composed "
         "of a number of stones worn flat by years of water erosion. "
         "Cracks between them are wide enough to see through to the "
         "water beneath but not large enough to fall through.%^RESET%^"
   ]));
   set_search("default","%^BOLD%^%^BLACK%^As you search the area, you catch "
      "sight of faint %^RESET%^si%^BOLD%^l%^RESET%^ver%^BOLD%^y i%^RESET%^ns"
      "%^BOLD%^c%^RESET%^rip%^BOLD%^t%^RESET%^io%^BOLD%^n%^RESET%^s %^BOLD%^"
      "%^BLACK%^carved into the columns.%^RESET%^");
   set_exits(([
      "west" : ROOMS"midnight_river"
   ]));
}

/*
Isto  Outside Night Mode
Tangi  Outside Day Mode
Shunveil  Revert To Standard Mode
*/

void init(){
   ::init();
   add_action("isto","isto");
   add_action("tangi","tangi");
   add_action("shunveil","shunveil");
   add_action("isto","Isto");
   add_action("tangi","Tangi");
   add_action("shunveil","Shunveil");
   add_action("read_em","read");
}

int read_em(string str){
   if(!str) return 0;
   if(str != "column" && str != "columns" && str != "inscription" && str != "inscriptions") return 0;
   tell_object(TP,"%^BOLD%^%^WHITE%^You study the columns and make sense "
      "of three words: %^BOLD%^%^BLACK%^Shunveil%^WHITE%^, %^RESET%^%^GREEN%^Tangi"
      "%^BOLD%^%^WHITE%^, and %^CYAN%^Isto%^WHITE%^.%^RESET%^");
   if(!TP->query_invis()){
      tell_room(TO,""+TPQCN+" steps close to the columns, studying them intently.",TP);
   }
   return 1;
}

int shunveil(){
   tell_object(TP,"%^BOLD%^%^BLACK%^You utter the word, 'Shunveil' "
      "and the air literally hums with arcane energy as the lush "
      "forest and beautiful sky fade to reveal the true appearance "
      "of the grotto.%^RESET%^");
   tell_room(TO,"%^BOLD%^%^BLACK%^"+TPQCN+"%^BOLD%^%^BLACK%^ utters the word, 'Shunveil' "
      "and the air literally hums with arcane energy as the lush "
      "forest and beautiful sky fade to reveal the true appearance "
      "of the grotto.%^RESET%^",TP);
   set_long("%^BOLD%^%^BLACK%^D%^CYAN%^a%^BLACK%^mp stone surrounds "
      "you here, %^CYAN%^flu%^GREEN%^o%^CYAN%^r%^RESET%^%^CYAN%^e"
      "%^BOLD%^%^CYAN%^sc%^GREEN%^e%^CYAN%^nt l%^WHITE%^i%^CYAN%^"
      "ch%^GREEN%^e%^CYAN%^n %^BLACK%^clinging to the walls and "
      "ceiling in thick patches that lend the area minimal "
      "%^WHITE%^illumination%^BLACK%^. Massive stalactites hang "
      "from the soaring ceiling, %^RESET%^%^CYAN%^mo%^BOLD%^"
      "%^CYAN%^i%^RESET%^%^CYAN%^st%^GREEN%^u%^CYAN%^re %^BOLD%^"
      "%^BLACK%^slowly gathering to drip into the %^RESET%^"
      "%^CYAN%^w%^BOLD%^%^BLUE%^a%^RESET%^%^CYAN%^t%^BOLD%^"
      "%^CYAN%^e%^RESET%^%^CYAN%^r %^BOLD%^%^BLACK%^below. The "
      "cavern houses two %^CYAN%^pools %^BLACK%^separated by "
      "a precipice. The larger of the two is located on the "
      "lower plain and is quite expansive. %^WHITE%^Cr%^CYAN%^y"
      "%^WHITE%^stal cl%^CYAN%^e%^RESET%^%^CYAN%^a%^BOLD%^"
      "%^WHITE%^r wat%^CYAN%^e%^WHITE%^r %^BLACK%^resides within, "
      "revealing a deep rocky bottom lit by %^CYAN%^flu%^GREEN%^o"
      "%^CYAN%^r%^RESET%^%^CYAN%^e%^BOLD%^%^CYAN%^sc%^GREEN%^e"
      "%^CYAN%^nt aqu%^GREEN%^a%^CYAN%^t%^RESET%^%^CYAN%^i%^BOLD"
      "%^%^CYAN%^c pl%^RESET%^%^GREEN%^a%^BOLD%^%^CYAN%^nt "
      "l%^RESET%^%^CYAN%^i%^BOLD%^%^CYAN%^fe%^BLACK%^. Gl"
      "%^WHITE%^i%^BLACK%^tt%^RESET%^e%^BOLD%^%^BLACK%^r%^WHITE%^"
      "i%^BLACK%^ng g%^MAGENTA%^e%^BLACK%^mst%^CYAN%^o%^BLACK%^n"
      "%^WHITE%^e%^BLACK%^s dot the %^RESET%^%^ORANGE%^rough "
      "r%^WHITE%^o%^ORANGE%^cks%^BOLD%^%^BLACK%^. Along the "
      "northeastern corner of the wall a set of stone steps "
      "ascend to the upper tier of the %^RESET%^%^CYAN%^grotto"
      "%^BOLD%^%^BLACK%^. %^RESET%^Steam %^BOLD%^%^BLACK%^rises "
      "from the %^CYAN%^smaller pool%^BLACK%^. Its location and "
      "size makes for a more intimate, %^RESET%^%^RED%^rom"
      "%^MAGENTA%^a%^RED%^ntic atm%^MAGENTA%^o%^RED%^sph%^BOLD%^"
      "%^RED%^e%^RESET%^%^RED%^re%^BOLD%^%^BLACK%^. Suspended "
      "between a pair of natural columns near the heated pool "
      "is a sturdy sp%^WHITE%^i%^BLACK%^d%^RED%^e%^BLACK%^r"
      "%^RESET%^s%^BOLD%^%^WHITE%^i%^RESET%^lk h%^BOLD%^%^RED%^a"
      "%^RESET%^mmo%^BOLD%^%^WHITE%^c%^RESET%^k%^BOLD%^%^BLACK%^. "
      "Both pools appear to be fed by an %^RESET%^%^CYAN%^"
      "underground stream%^BOLD%^%^BLACK%^, the %^CYAN%^w%^RESET%^"
      "%^CYAN%^a%^BOLD%^%^CYAN%^ter fl%^RESET%^%^CYAN%^o%^BOLD%^"
      "%^CYAN%^w%^BLUE%^i%^CYAN%^ng %^BLACK%^through unseen "
      "cr%^RESET%^e%^BOLD%^%^BLACK%^vices, resulting in a lazy "
      "current. Around the pools the stalagmites have been "
      "reshaped into statuary and seating. %^RESET%^Adamantium "
      "braziers %^BOLD%^%^BLACK%^are suspended from the "
      "stalactites hanging from the grotto's ceiling, %^RESET%^"
      "%^ORANGE%^fr%^RED%^a%^ORANGE%^gr%^MAGENTA%^a%^ORANGE%^nt "
      "ch%^BOLD%^%^RED%^i%^RESET%^%^ORANGE%^ps %^BOLD%^%^BLACK%^"
      "b%^RED%^u%^BLACK%^rning within.%^RESET%^\n");
   set_smell("default","%^RESET%^%^CYAN%^The braziers release an intoxicating fragrance.%^RESET%^");
   set_listen("default","%^BOLD%^%^BLACK%^The sound of running water echoes off the cavern walls.%^RESET%^");
   set_items(([
      ({"braziers","brazier"}) : "%^BOLD%^%^BLACK%^Diamond-shaped "
         "%^RESET%^adamatium braziers %^BOLD%^%^BLACK%^hang from "
         "chains anchored to the stalactites. Pale %^RESET%^sm%^BOLD%^"
         "%^WHITE%^o%^RESET%^ke %^BOLD%^%^BLACK%^spills from tiny "
         "perforations made in the metal. The scent released from "
         "the braziers is %^RESET%^%^MAGENTA%^int%^RED%^o%^MAGENTA%^"
         "xicating%^BOLD%^%^BLACK%^.%^RESET%^",
      ({"stalactites","stalactite","ceiling"}) : "%^BOLD%^%^BLACK%^Thick, "
         "jagged stalactites hang from the cavernous ceiling. They are "
         "coated in %^WHITE%^wh%^RESET%^i%^BOLD%^%^WHITE%^te c%^BLACK%^a"
         "%^WHITE%^lcium %^BLACK%^deposits and %^RESET%^%^CYAN%^"
         "precipitation%^BOLD%^%^BLACK%^. Diamond-shaped %^RESET%^"
         "adamantium braziers %^BOLD%^%^BLACK%^hang from many of the "
         "stalactites.%^RESET%^",
      ({"stalagmites","stalagmite","bench","benches","statues","statue"}) :
         "%^BOLD%^%^BLACK%^Sizable stalagmites emerge from the "
         "grotto's stone floor. Many have been reshaped into seating and "
         "statuary by an artist with a keen eye for detail. Both the "
         "benches and statues are wreathed in shad%^RESET%^%^BLUE%^o"
         "%^BOLD%^%^BLACK%^wy t%^RESET%^e%^BOLD%^%^BLACK%^ndrils. "
         "Graceful and lithe each of the effigies is a life-size "
         "depiction of a nude, dancing elf. Their specific lineages "
         "indiscernible, there are %^RESET%^%^MAGENTA%^females "
         "%^BOLD%^%^BLACK%^as well as %^RESET%^%^RED%^males %^BOLD%^"
         "%^BLACK%^present, and all are %^CYAN%^br%^RESET%^%^CYAN%^"
         "ea%^BOLD%^%^CYAN%^thtak%^WHITE%^i%^CYAN%^ng %^BLACK%^to behold.%^RESET%^",
      ({"hammock","columns","column"}) : "%^BOLD%^%^BLACK%^These two "
         "natural columns reach to the ceiling of the grotto. Situated "
         "near the hot spring they have a sp%^WHITE%^i%^BLACK%^d%^RED%^"
         "e%^BLACK%^r%^RESET%^s%^BOLD%^%^WHITE%^i%^RESET%^lk h%^BOLD%^"
         "%^RED%^a%^RESET%^mmo%^BOLD%^%^WHITE%^c%^RESET%^k %^BOLD%^"
         "%^BLACK%^stretched between them. The %^WHITE%^w%^RESET%^e"
         "%^BOLD%^%^WHITE%^b %^BLACK%^pattern of the %^WHITE%^s%^RED%^"
         "i%^WHITE%^lk %^BLACK%^is as intricate and myriad in design "
         "as one woven by an actual sp%^RED%^i%^BLACK%^der. A soft "
         "%^WHITE%^glow %^BLACK%^surrounds the hammock itself as "
         "%^WHITE%^l%^RESET%^i%^BOLD%^%^WHITE%^ght tr%^RESET%^a"
         "%^BOLD%^%^WHITE%^ils %^BOLD%^%^BLACK%^course through the "
         "s%^WHITE%^i%^BLACK%^l%^CYAN%^v%^RESET%^e%^BOLD%^%^BLACK%^ry "
         "material, providing a stunning %^WHITE%^highlighting "
         "%^BLACK%^effect.%^RESET%^",
      "pool 1" : "%^BOLD%^%^BLACK%^This large %^BOLD%^%^WHITE%^cr"
         "%^CYAN%^y%^WHITE%^stall%^RESET%^%^CYAN%^i%^BOLD%^%^WHITE%^ne "
         "p%^CYAN%^o%^RESET%^%^CYAN%^o%^BOLD%^%^WHITE%^l %^BLACK%^"
         "occupies a majority of the lower level of the grotto. "
         "Smooth long rocks border the pool and are a perfect place "
         "for lounging. A few %^RESET%^%^ORANGE%^thatch mats %^BOLD%^"
         "%^BLACK%^have been lain out for just that purpose. "
         "Illuminated by %^CYAN%^flu%^GREEN%^o%^CYAN%^r%^RESET%^"
         "%^CYAN%^e%^BOLD%^%^CYAN%^sc%^GREEN%^e%^CYAN%^nt aqu"
         "%^GREEN%^a%^CYAN%^t%^RESET%^%^CYAN%^i%^BOLD%^%^CYAN%^c "
         "pl%^RESET%^%^GREEN%^a%^BOLD%^%^CYAN%^nt l%^RESET%^%^CYAN%^i"
         "%^BOLD%^%^CYAN%^fe%^BLACK%^ you can see straight through "
         "the water to the bottom, which is quite deep toward the "
         "middle. The rocky floor is studded with gl%^WHITE%^i"
         "%^BLACK%^tt%^RESET%^e%^BOLD%^%^BLACK%^ring %^MAGENTA%^g"
         "%^RESET%^%^MAGENTA%^e%^BOLD%^%^MAGENTA%^m%^BLACK%^st"
         "%^RESET%^o%^BOLD%^%^BLACK%^ne deposits. A very faint "
         "current causes the water to circle lazily.%^RESET%^",
      "pool 2" : "%^BOLD%^%^BLACK%^Directly north of the %^CYAN%^"
         "larger pool %^BLACK%^a rock face rises about twenty "
         "feet off the ground. A set of stairs has been carved "
         "from the side of the small cliff and winds around it. "
         "They lead to a smaller %^RESET%^%^RED%^hot spring "
         "%^BOLD%^%^BLACK%^that exists at the top. %^RESET%^Steam"
         "%^BOLD%^%^BLACK%^ rises off the surface of the %^CYAN%^"
         "clear water%^BLACK%^, which circles lazily. Due to the "
         "fact that it is much shallower than the pool below, and "
         "truly only meant for lounging, a circular bench has been "
         "carved from the interior perimeter. The %^GREEN%^pl%^CYAN%^"
         "a%^GREEN%^nt l%^RESET%^%^CYAN%^i%^BOLD%^%^GREEN%^fe %^BLACK%^"
         "has also been cleared away and the floor leveled. To the east "
         "of the pool are two natural columns that extend from the top "
         "of the peak of the steep hill to the ceiling. Stretched "
         "between them is a sturdy sp%^RED%^i%^BLACK%^d%^WHITE%^er"
         "%^RESET%^s%^BOLD%^%^WHITE%^i%^RESET%^lk h%^BOLD%^%^RED%^a"
         "%^RESET%^mmo%^BOLD%^%^WHITE%^c%^RESET%^k%^BOLD%^%^BLACK%^.%^RESET%^",
      ({"floor","ground"}) : "%^BOLD%^%^BLACK%^The floor is composed "
         "of a number of stones worn flat by years of water erosion. "
         "Cracks between them are wide enough to see through to the "
         "water beneath but not large enough to fall through.%^RESET%^"
   ]));
   return 1;
}

int tangi(){
   tell_object(TP,"%^RESET%^%^GREEN%^You utter the word, 'Tangi' "
      "and the grotto begins to transform. The air literally hums "
      "with arcane energy as the stone surfaces recede only to be "
      "replaced by lush forest, soft grass and a pale blue sky lit "
      "by a dazzling sun.%^RESET%^");
   tell_room(TO,"%^RESET%^%^GREEN%^"+TPQCN+"%^RESET%^%^GREEN%^ utters the word, 'Tangi' "
      "and the grotto begins to transform. The air literally hums "
      "with arcane energy as the stone surfaces recede only to be "
      "replaced by lush forest, soft grass and a pale blue sky lit "
      "by a dazzling sun.%^RESET%^",TP);
   set_long("%^RESET%^%^GREEN%^You have entered a spacious clearing "
      "surrounded by tall trees. A heavy canopy of v%^BOLD%^%^GREEN%^e"
      "%^RESET%^%^GREEN%^rd%^CYAN%^a%^GREEN%^nt lea%^BOLD%^%^GREEN%^v"
      "%^RESET%^%^GREEN%^es casts the grassy forest floor in ample "
      "%^BOLD%^%^BLACK%^shade%^RESET%^%^GREEN%^. The %^BOLD%^%^ORANGE%^"
      "sun %^RESET%^%^GREEN%^looms near but does not cause uncomfortable "
      "heat or glare, only illuminating the details of the clearing, "
      "which houses two %^BOLD%^%^WHITE%^cr%^CYAN%^y%^WHITE%^st%^RESET%^a"
      "%^BOLD%^%^WHITE%^lline p%^CYAN%^o%^RESET%^%^CYAN%^o%^BOLD%^%^WHITE%^ls "
      "%^RESET%^%^GREEN%^separated by a %^BOLD%^%^BLACK%^precipice%^RESET%^"
      "%^GREEN%^. The larger of the two is located on the lower plain and "
      "is quite expansive. Crystal %^BOLD%^%^CYAN%^clear water %^RESET%^"
      "%^GREEN%^resides within, revealing a %^BOLD%^%^BLACK%^ro%^RESET%^"
      "%^ORANGE%^c%^BOLD%^%^BLACK%^ky bottom %^RESET%^%^GREEN%^that is "
      "quite deep toward the center. %^BOLD%^%^BLACK%^Gl%^WHITE%^i%^BLACK%^"
      "tt%^RESET%^e%^BOLD%^%^BLACK%^ring %^MAGENTA%^g%^RESET%^%^MAGENTA%^e"
      "%^BOLD%^%^MAGENTA%^m%^BLACK%^st%^RESET%^o%^BOLD%^%^BLACK%^nes "
      "%^RESET%^%^GREEN%^dot the rough rocks. Directly north of the cool "
      "pool is a tall rock face. A crude staircase has been fashioned "
      "from the stone at the side of the cliff, which leads to the second "
      "pool. %^WHITE%^Steam %^GREEN%^rises from the smaller pool. Its "
      "location and size makes for a more intimate, %^RESET%^%^RED%^rom"
      "%^MAGENTA%^a%^RED%^ntic atm%^MAGENTA%^o%^RED%^sph%^BOLD%^%^RED%^e"
      "%^RESET%^%^RED%^re%^GREEN%^. Suspended between two marble pillars "
      "near the heated pool is a sturdy %^BOLD%^%^BLACK%^sp%^RED%^i%^BLACK%^"
      "d%^WHITE%^e%^BLACK%^r%^RESET%^s%^BOLD%^%^WHITE%^i%^RESET%^lk h%^BOLD%^"
      "%^RED%^a%^RESET%^mmo%^BOLD%^%^WHITE%^c%^RESET%^k%^GREEN%^. Both pools "
      "appear to be fed by an %^CYAN%^underground stream%^GREEN%^, the water "
      "flowing through unseen crevices, resulting in a lazy current. %^BOLD%^"
      "%^WHITE%^White marble benches %^RESET%^%^GREEN%^and statues surround "
      "the two pools. %^WHITE%^P%^BOLD%^%^WHITE%^a%^RESET%^le fl%^BOLD%^"
      "%^WHITE%^o%^RESET%^wers %^GREEN%^grow in thick patches wherever there "
      "is grass, filling the clearing with their heady scent.%^RESET%^\n");
   set_smell("default","%^RESET%^%^CYAN%^The pale flowers emit an intoxicating fragrance.%^RESET%^");
   set_listen("default","%^BOLD%^%^BLACK%^Birds call cheerfully to one another and the leaves rustle on occasion.%^RESET%^");
   set_items(([
      ({"statues","statue","bench","benches"}) : "%^RESET%^%^GREEN%^An "
         "artist with a keen eye for detail has shaped %^BOLD%^%^WHITE%^"
         "pristine white marble%^RESET%^%^GREEN%^ into sturdy benches and "
         "elegant statuary that decorate the clearing. The benches are "
         "wreathed in carvings of l%^BOLD%^%^GREEN%^e%^RESET%^%^GREEN%^"
         "av%^CYAN%^e%^GREEN%^s and %^BOLD%^%^MAGENTA%^fl%^RESET%^%^MAGENTA%^o"
         "%^BOLD%^%^MAGENTA%^wers%^RESET%^%^GREEN%^, giving them a somewhat "
         "feminine flair. Graceful and lithe each of the statues is a life-size "
         "depiction of a nude, dancing elf. Their specific lineages indiscernible, "
         "there are %^MAGENTA%^females %^GREEN%^as well as %^RED%^males "
         "%^GREEN%^present, and all are %^CYAN%^br%^BOLD%^%^CYAN%^ea%^RESET%^"
         "%^CYAN%^thtaking %^GREEN%^to behold.%^RESET%^",
      ({"trees","tree","canopy"}) : "%^RESET%^%^GREEN%^Tall trees surround "
         "the clearing except to the south where the path leads back in to "
         "the forest. A canopy of large verdant leaves casts long shadows "
         "across both pools.%^RESET%^",
      "hammock" : "%^RESET%^%^GREEN%^These two %^BOLD%^%^WHITE%^marble columns "
         "%^RESET%^%^GREEN%^reach toward the sky. Situated near the %^RED%^hot "
         "spring %^GREEN%^they have a %^BOLD%^%^BLACK%^sp%^RED%^i%^BLACK%^d"
         "%^WHITE%^e%^BLACK%^r%^RESET%^s%^BOLD%^%^WHITE%^i%^RESET%^lk "
         "h%^BOLD%^%^RED%^a%^RESET%^mmo%^BOLD%^%^WHITE%^c%^RESET%^k %^GREEN%^"
         "stretched between them. The %^WHITE%^w%^RESET%^e%^BOLD%^%^WHITE%^b "
         "%^RESET%^%^GREEN%^pattern of the %^WHITE%^s%^RED%^i%^WHITE%^lk "
         "%^RESET%^%^GREEN%^is as intricate and myriad in design as one "
         "woven by an actual %^BOLD%^%^BLACK%^sp%^RED%^i%^BLACK%^der%^RESET%^"
         "%^GREEN%^. A soft %^WHITE%^glow %^GREEN%^surrounds the hammock "
         "itself as %^WHITE%^l%^RESET%^i%^BOLD%^%^WHITE%^ght tr%^RESET%^a"
         "%^BOLD%^%^WHITE%^ils %^RESET%^%^GREEN%^course through the %^RESET%^"
         "s%^WHITE%^i%^BLACK%^l%^CYAN%^v%^RESET%^e%^BOLD%^%^BLACK%^r%^RESET%^y "
         "%^GREEN%^material, providing a stunning %^WHITE%^highlighting %^GREEN%^effect.%^RESET%^",
      "sky" : "%^BOLD%^%^GREEN%^It is a clear, blue beautiful %^BOLD%^"
         "%^CYAN%^sky %^RESET%^%^GREEN%^lit by a %^BOLD%^%^ORANGE%^yellow "
         "sun%^RESET%^%^GREEN%^. Somehow, despite looming so near, the star "
         "does not seem to generate too much %^RED%^heat %^GREEN%^nor is it "
         "%^BOLD%^%^BLACK%^blinding%^RESET%^%^GREEN%^. In addition to this, "
         "the %^BOLD%^%^BLACK%^shade %^RESET%^%^GREEN%^created by the thick "
         "c%^BOLD%^%^GREEN%^a%^RESET%^%^GREEN%^n%^CYAN%^o%^GREEN%^py keeps "
         "the area%^BOLD%^%^CYAN%^ cool %^RESET%^%^GREEN%^and comfortable.%^RESET%^",
      "pool 1" : "%^RESET%^%^GREEN%^This large %^BOLD%^%^WHITE%^cr%^CYAN%^y"
         "%^WHITE%^stall%^RESET%^%^CYAN%^i%^BOLD%^%^WHITE%^ne p%^CYAN%^o"
         "%^RESET%^%^CYAN%^o%^BOLD%^%^WHITE%^l %^RESET%^%^GREEN%^occupies "
         "a majority of the clearing. The grass recedes near the water and "
         "smooth %^BOLD%^%^BLACK%^long rocks %^RESET%^%^GREEN%^border the "
         "pool and are a perfect place for lounging. A few %^ORANGE%^thatch "
         "mats %^GREEN%^have been lain out for just that purpose. Illuminated "
         "by %^BOLD%^%^CYAN%^flu%^GREEN%^o%^CYAN%^r%^RESET%^%^CYAN%^e%^BOLD%^"
         "%^CYAN%^sc%^GREEN%^e%^CYAN%^nt aqu%^GREEN%^a%^CYAN%^t%^RESET%^"
         "%^CYAN%^i%^BOLD%^%^CYAN%^c pl%^RESET%^%^GREEN%^a%^BOLD%^%^CYAN%^nt "
         "l%^RESET%^%^CYAN%^i%^BOLD%^%^CYAN%^fe%^RESET%^%^GREEN%^ you can "
         "see straight through the water to the bottom, which is quite deep "
         "toward the middle. The rocky floor is studded with %^BOLD%^"
         "%^BLACK%^gl%^WHITE%^i%^BLACK%^tt%^RESET%^e%^BOLD%^%^BLACK%^ring "
         "%^MAGENTA%^g%^RESET%^%^MAGENTA%^e%^BOLD%^%^MAGENTA%^m%^BLACK%^st"
         "%^RESET%^o%^BOLD%^%^BLACK%^ne %^RESET%^%^GREEN%^deposits. A very "
         "faint current causes the water to circle lazily.%^RESET%^",
      "pool 2" : "%^RESET%^%^GREEN%^Directly north of the %^BOLD%^%^CYAN%^"
         "larger pool %^RESET%^%^GREEN%^a %^BOLD%^%^BLACK%^ro%^RESET%^"
         "%^ORANGE%^c%^BOLD%^%^BLACK%^k face %^RESET%^%^GREEN%^rises about "
         "twenty feet off the ground. A set of %^BOLD%^%^BLACK%^stairs "
         "%^RESET%^%^GREEN%^has been carved from the side of the small "
         "cliff and winds around it. They lead to a smaller%^RED%^ hot "
         "spring %^GREEN%^that exists at the top. %^WHITE%^Steam "
         "%^GREEN%^rises off the surface of the clear water, which "
         "circles lazily. Due to the fact that it is much shallower than "
         "the pool below, and truly only meant for lounging, a circular "
         "bench has been carved from the interior perimeter. The %^BOLD%^"
         "%^GREEN%^pl%^CYAN%^a%^GREEN%^nt l%^RESET%^%^CYAN%^i%^BOLD%^"
         "%^GREEN%^fe %^RESET%^%^GREEN%^has also been cleared away and "
         "the floor leveled. To the east of the pool are two marble "
         "%^BOLD%^%^WHITE%^columns %^RESET%^%^GREEN%^that extend from "
         "the top of the peak of the steep hill to the ceiling. Stretched "
         "between them is a sturdy %^BOLD%^%^BLACK%^sp%^RED%^i%^BLACK%^d"
         "%^WHITE%^e%^BLACK%^r%^RESET%^s%^BOLD%^%^WHITE%^i%^RESET%^lk "
         "h%^BOLD%^%^RED%^a%^RESET%^mmo%^BOLD%^%^WHITE%^c%^RESET%^k%^GREEN%^.%^RESET%^",
      ({"flower","flowers","ground"}) : "%^RESET%^%^GREEN%^Thick patches "
         "of tiny, %^WHITE%^wh%^BOLD%^%^WHITE%^i%^RESET%^te fl%^BOLD%^"
         "%^WHITE%^o%^RESET%^wers %^GREEN%^carpet the forest floor. They "
         "emit a %^BOLD%^%^MAGENTA%^sweet %^RESET%^%^GREEN%^scent but "
         "are not overpowering despite their number. The gr%^BOLD%^"
         "%^GREEN%^a%^RESET%^%^GREEN%^ss begins to recede as near the "
         "%^CYAN%^pools %^GREEN%^and is replaced by long %^BOLD%^"
         "%^BLACK%^flat stones %^RESET%^%^GREEN%^perfect for %^BOLD%^"
         "%^ORANGE%^s%^RESET%^%^ORANGE%^u%^BOLD%^%^ORANGE%^nning%^RESET%^%^GREEN%^.%^RESET%^"
   ]));
   return 1;
}

int isto(){
   tell_object(TP,"%^BOLD%^%^BLUE%^You utter the word, 'Isto' and "
      "the grotto begins to transform. The air literally hums with "
      "arcane energy as the stone surfaces recede only to be replaced "
      "by a rich nighttime sky filled with bright stars, a lush forest "
      "and soft grass.%^RESET%^");
   tell_room(TO,"%^BOLD%^%^BLUE%^"+TPQCN+" %^BOLD%^%^BLUE%^utters the word, 'Isto' and "
      "the grotto begins to transform. The air literally hums with "
      "arcane energy as the stone surfaces recede only to be replaced "
      "by a rich nighttime sky filled with bright stars, a lush forest "
      "and soft grass.%^RESET%^",TP);
   set_long("%^RESET%^%^GREEN%^You have entered a spacious clearing "
      "surrounded by tall trees. The sky above is a rich %^BOLD%^"
      "%^BLUE%^midnight blue %^RESET%^%^GREEN%^lit by a full %^BOLD%^"
      "%^BLACK%^m%^CYAN%^o%^RESET%^%^CYAN%^o%^BOLD%^%^BLACK%^n "
      "%^RESET%^%^GREEN%^and dozens of %^BOLD%^%^WHITE%^sp%^ORANGE%^"
      "a%^WHITE%^rkl%^CYAN%^i%^WHITE%^ng st%^BLACK%^a%^WHITE%^rs"
      "%^RESET%^%^GREEN%^, their %^WHITE%^s%^BOLD%^%^CYAN%^i"
      "%^RESET%^lv%^BOLD%^%^BLACK%^e%^RESET%^ry l%^BOLD%^%^CYAN%^"
      "i%^ORANGE%^g%^RESET%^ht %^GREEN%^playing off the v%^BOLD%^"
      "%^GREEN%^e%^RESET%^%^GREEN%^rd%^CYAN%^a%^GREEN%^nt canopy. "
      "The clearing houses two %^BOLD%^%^BLUE%^pools %^RESET%^"
      "%^GREEN%^separated by a %^BOLD%^%^BLACK%^precipice%^RESET%^"
      "%^GREEN%^. The larger of the two is located on the lower "
      "plain and is quite expansive, its surface gleaming in the "
      "gentle %^WHITE%^s%^BOLD%^%^BLACK%^t%^CYAN%^a%^BLACK%^r"
      "%^RESET%^l%^BOLD%^%^ORANGE%^i%^RESET%^ght%^GREEN%^. In the "
      "%^BLUE%^darkness %^GREEN%^the water appears %^BOLD%^%^BLACK%^"
      "pitch black %^RESET%^%^GREEN%^and it is impossible to "
      "determine how deep the pool is. Directly north of the cool "
      "pool is a tall %^BOLD%^%^BLACK%^ro%^RESET%^%^ORANGE%^c"
      "%^BOLD%^%^BLACK%^k face%^RESET%^%^GREEN%^. A crude %^BOLD%^"
      "%^BLACK%^staircase %^RESET%^%^GREEN%^has been fashioned "
      "from the stone at the side of the cliff, which leads to "
      "the second pool. %^WHITE%^Steam %^GREEN%^rises from the "
      "smaller pool. Its location and size makes for a more "
      "intimate, %^RED%^rom%^MAGENTA%^a%^RED%^ntic atm%^MAGENTA%^o"
      "%^RED%^sph%^BOLD%^%^RED%^e%^RESET%^%^RED%^re%^GREEN%^. "
      "Suspended between two %^BOLD%^%^WHITE%^marble pillars "
      "%^RESET%^%^GREEN%^near the heated pool is a sturdy "
      "%^BOLD%^%^BLACK%^sp%^RED%^i%^BLACK%^d%^WHITE%^e%^BLACK%^r"
      "%^RESET%^s%^BOLD%^%^WHITE%^i%^RESET%^lk h%^BOLD%^%^RED%^a"
      "%^RESET%^mmo%^BOLD%^%^WHITE%^c%^RESET%^k%^GREEN%^. Both "
      "pools appear to be fed by an %^CYAN%^underground stream"
      "%^GREEN%^, the water flowing through unseen crevices, "
      "resulting in a lazy current. %^BOLD%^%^WHITE%^White "
      "marble benches %^RESET%^%^GREEN%^and %^BOLD%^%^WHITE%^"
      "statues %^RESET%^%^GREEN%^surround the two pools. Luminescent "
      "%^WHITE%^wh%^BOLD%^%^WHITE%^i%^RESET%^te fl%^BOLD%^"
      "%^WHITE%^o%^RESET%^wers %^GREEN%^grow in thick patches "
      "wherever there is gr%^BOLD%^%^GREEN%^a%^RESET%^%^GREEN%^ss, "
      "filling the clearing with their heady scent.%^RESET%^\n");
   set_smell("default","%^RESET%^%^CYAN%^The pale flowers emit an intoxicating fragrance.%^RESET%^");
   set_listen("default","%^BOLD%^%^BLACK%^Owls hoot frequently and the leaves rustle as unseen residents traverse the surrounding forest.%^RESET%^");
   set_items(([
      ({"statues","statue","bench","benches"}) : "%^RESET%^%^GREEN%^An "
         "artist with a keen eye for detail has shaped %^BOLD%^%^WHITE%^"
         "pristine white marble%^RESET%^%^GREEN%^ into sturdy benches "
         "and elegant statuary that decorate the clearing. The benches "
         "are wreathed in carvings of l%^BOLD%^%^GREEN%^e%^RESET%^"
         "%^GREEN%^av%^CYAN%^e%^GREEN%^s and %^BOLD%^%^MAGENTA%^fl"
         "%^RESET%^%^MAGENTA%^o%^BOLD%^%^MAGENTA%^wers%^RESET%^%^GREEN%^, "
         "giving them a somewhat feminine flair. Graceful and lithe each "
         "of the statues is a life-size depiction of a nude, dancing "
         "elf. Their specific lineages indiscernible, there are "
         "%^MAGENTA%^females %^GREEN%^as well as %^RED%^males "
         "%^GREEN%^present, and all are %^CYAN%^br%^BOLD%^%^CYAN%^ea"
         "%^RESET%^%^CYAN%^thtaking %^GREEN%^to behold.%^RESET%^",
      ({"trees","tree","canopy"}) : "%^RESET%^%^GREEN%^Tall trees "
         "surround the clearing except to the south where the path "
         "leads back in to the forest. The %^WHITE%^s%^BOLD%^%^BLACK%^"
         "t%^CYAN%^a%^BLACK%^r%^RESET%^l%^BOLD%^%^ORANGE%^i%^WHITE%^"
         "ght h%^CYAN%^i%^WHITE%^ghl%^ORANGE%^i%^WHITE%^ghts %^RESET%^"
         "%^GREEN%^a canopy of large v%^BOLD%^%^GREEN%^e%^RESET%^"
         "%^GREEN%^rd%^CYAN%^a%^GREEN%^nt l%^BOLD%^%^GREEN%^e%^RESET%^%^GREEN%^aves.%^RESET%^",
      "hammock" : "%^RESET%^%^GREEN%^These two %^BOLD%^%^WHITE%^marble columns "
         "%^RESET%^%^GREEN%^reach toward the sky. Situated near the %^RED%^hot "
         "spring %^GREEN%^they have a %^BOLD%^%^BLACK%^sp%^RED%^i%^BLACK%^d"
         "%^WHITE%^e%^BLACK%^r%^RESET%^s%^BOLD%^%^WHITE%^i%^RESET%^lk "
         "h%^BOLD%^%^RED%^a%^RESET%^mmo%^BOLD%^%^WHITE%^c%^RESET%^k %^GREEN%^"
         "stretched between them. The %^WHITE%^w%^RESET%^e%^BOLD%^%^WHITE%^b "
         "%^RESET%^%^GREEN%^pattern of the %^WHITE%^s%^RED%^i%^WHITE%^lk "
         "%^RESET%^%^GREEN%^is as intricate and myriad in design as one "
         "woven by an actual %^BOLD%^%^BLACK%^sp%^RED%^i%^BLACK%^der%^RESET%^"
         "%^GREEN%^. A soft %^WHITE%^glow %^GREEN%^surrounds the hammock "
         "itself as %^WHITE%^l%^RESET%^i%^BOLD%^%^WHITE%^ght tr%^RESET%^a"
         "%^BOLD%^%^WHITE%^ils %^RESET%^%^GREEN%^course through the %^RESET%^"
         "s%^WHITE%^i%^BLACK%^l%^CYAN%^v%^RESET%^e%^BOLD%^%^BLACK%^r%^RESET%^y "
         "%^GREEN%^material, providing a stunning %^WHITE%^highlighting %^GREEN%^effect.%^RESET%^",
      "sky" : "%^RESET%^%^BLUE%^It is a clear %^BOLD%^%^BLUE%^midnight "
         "blue sky %^RESET%^%^BLUE%^lit by a full %^BOLD%^%^BLACK%^m%^CYAN%^"
         "o%^RESET%^%^CYAN%^o%^BOLD%^%^BLACK%^n %^RESET%^%^BLUE%^and "
         "countless %^WHITE%^s%^BOLD%^%^ORANGE%^t%^CYAN%^a%^ORANGE%^r"
         "%^RESET%^s%^GREEN%^.%^RESET%^",
      "pool 1" : "%^RESET%^%^GREEN%^This large %^BOLD%^%^CYAN%^cool pool "
         "%^RESET%^%^GREEN%^occupies a majority of the clearing. The "
         "gr%^BOLD%^%^GREEN%^a%^RESET%^%^GREEN%^ss recedes near the "
         "water and smooth %^BOLD%^%^BLACK%^long rocks %^RESET%^"
         "%^GREEN%^border the pool and are a perfect place for lounging. "
         "A few %^ORANGE%^thatch mats %^GREEN%^have been lain out for "
         "just that purpose. The waters appearance is akin to a well "
         "of %^BLUE%^black ink%^GREEN%^. The %^WHITE%^s%^BOLD%^%^ORANGE%^t"
         "%^CYAN%^a%^ORANGE%^r%^RESET%^light %^GREEN%^reflects off the "
         "water but does not penetrate the surface. A very faint "
         "current causes the water to circle lazily.%^RESET%^",
      "pool 2" : "%^RESET%^%^GREEN%^Directly north of the larger pool "
         "a %^BOLD%^%^BLACK%^ro%^RESET%^%^ORANGE%^c%^BOLD%^%^BLACK%^k "
         "face%^RESET%^%^GREEN%^ rises about twenty feet off the ground. "
         "A set of %^BOLD%^%^BLACK%^stairs %^RESET%^%^GREEN%^has been carved "
         "from the side of the small cliff and winds around it. They lead to a "
         "smaller %^RED%^hot spring %^GREEN%^that exists at the top. "
         "%^WHITE%^Steam %^GREEN%^rises off the dark surface of the water, "
         "which circles lazily. Closer inspection reveals that this pool "
         "is shallow and truly only meant for lounging, so a circular bench "
         "has been carved from the interior perimeter. To the east of the "
         "pool are two %^BOLD%^%^WHITE%^marble columns %^RESET%^%^GREEN%^"
         "that extend from the top of the peak of the steep hill to the "
         "ceiling. Stretched between them is a sturdy %^BOLD%^%^BLACK%^sp"
         "%^RED%^i%^BLACK%^d%^WHITE%^e%^BLACK%^r%^RESET%^s%^BOLD%^%^WHITE%^i"
         "%^RESET%^lk h%^BOLD%^%^RED%^a%^RESET%^mmo%^BOLD%^%^WHITE%^c%^RESET%^k.%^RESET%^",
      ({"flower","flowers","ground"}) : "%^RESET%^%^GREEN%^Thick patches "
         "of tiny, %^WHITE%^wh%^BOLD%^%^WHITE%^i%^RESET%^te fl%^BOLD%^"
         "%^WHITE%^o%^RESET%^wers %^GREEN%^carpet the forest floor. They "
         "emit a %^BOLD%^%^MAGENTA%^sweet %^RESET%^%^GREEN%^scent but are "
         "not overpowering despite their number. The gr%^BOLD%^%^GREEN%^a"
         "%^RESET%^%^GREEN%^ss begins to recede as near the %^CYAN%^pools "
         "%^GREEN%^and is replaced by long %^BOLD%^%^BLACK%^flat stones "
         "%^RESET%^%^GREEN%^perfect for laying beneath the %^WHITE%^s%^BOLD%^"
         "%^ORANGE%^t%^CYAN%^a%^ORANGE%^r%^WHITE%^s%^GREEN%^.%^RESET%^"
   ]));
   return 1;
}
