//Ryzan and Aunuit's House
//Coded by ~Circe~ 7/24/13

#include <std.h>
#include "aunuit.h"

inherit AUNUIT;

void create()
{
    ::create();
    set_name("The Maw");
    set_short("%^BOLD%^%^BLACK%^The Maw%^RESET%^");
    set_long("%^BOLD%^%^BLACK%^A semi-circular da%^RESET%^i"
             "%^BOLD%^%^BLACK%^s occupies the southern wall where "
             "the main doors stand. A grand, %^RESET%^%^ORANGE%^darkwood "
             "staircase %^BOLD%^%^BLACK%^serves as the focal point of "
             "the room, occupying a majority of the northern quarter of "
             "the area with the exception of %^RESET%^%^MAGENTA%^ni%^BOLD%^"
             "%^MAGENTA%^c%^RESET%^%^MAGENTA%^hes %^BOLD%^%^BLACK%^reserved "
             "for relaxing and socializing. The floor is a beautiful, "
             "bla%^RESET%^c%^BOLD%^%^BLACK%^k m%^WHITE%^a%^BLACK%^rbl%^RESET%^e "
             "%^BOLD%^%^BLACK%^that has been buffed to a %^WHITE%^m%^RESET%^i"
             "%^BOLD%^%^WHITE%^r%^BLACK%^r%^RESET%^o%^BOLD%^%^WHITE%^r%^BLACK%^-"
             "like sheen. The dominant reflection belongs to the %^RED%^orn"
             "%^RESET%^%^RED%^a%^BOLD%^%^RED%^te ch%^RESET%^%^RED%^a%^BOLD%^"
             "%^RED%^ndel%^MAGENTA%^i%^RESET%^%^RED%^e%^BOLD%^%^RED%^r "
             "%^BLACK%^that hangs precariously between the base of the stairs "
             "and the entryway. The walls are lined with rich, %^RESET%^"
             "%^ORANGE%^darkwood panels %^BOLD%^%^BLACK%^and large %^WHITE%^"
             "scr%^RESET%^i%^BOLD%^%^WHITE%^ms%^RESET%^h%^BOLD%^%^ORANGE%^a"
             "%^BOLD%^%^WHITE%^w p%^RESET%^i%^BOLD%^%^WHITE%^ll%^ORANGE%^a"
             "%^WHITE%^rs %^BLACK%^which reach all the way to the concave "
             "ceiling. A large %^RESET%^%^MAGENTA%^f%^BOLD%^%^MAGENTA%^i"
             "%^WHITE%^r%^MAGENTA%^e%^RESET%^%^MAGENTA%^pla%^BOLD%^%^MAGENTA%^"
             "c%^RESET%^%^MAGENTA%^e %^BOLD%^%^BLACK%^dominates the northwest "
             "corner of the room and is surrounded by a rug and several "
             "comfortable looking %^WHITE%^seating options%^BLACK%^. Above "
             "the hearth is one of many %^RESET%^%^ORANGE%^oil %^RED%^p"
             "%^ORANGE%^a%^BOLD%^%^ORANGE%^i%^RESET%^%^GREEN%^n%^BOLD%^%^BLUE%^"
             "t%^MAGENTA%^i%^RESET%^%^MAGENTA%^n%^RED%^g%^ORANGE%^s %^BOLD%^"
             "%^BLACK%^featured throughout the room. A wide a%^RESET%^r%^BOLD%^"
             "%^BLACK%^chw%^WHITE%^a%^BLACK%^y leads to a hallway to the west "
             "and a narrow stairwell %^BOLD%^%^BLACK%^has been built beneath "
             "the staircase descending into %^RESET%^%^BLUE%^darkness%^BOLD%^%^BLACK%^.%^RESET%^\n");
    set_smell("default", "%^RESET%^%^CYAN%^The comfortable air in the room is tinged with a spicy musk.%^RESET%^");
    set_listen("default", "%^BOLD%^%^BLACK%^The room is quiet except for hushed conversations between nearby servants.%^RESET%^");
    set_items(([
                   ({ "floors", "floor" }) : "%^BOLD%^%^BLACK%^The floor is black "
                   "marble buffed to a m%^WHITE%^i%^RESET%^r%^BOLD%^%^BLACK%^r"
                   "%^WHITE%^o%^BLACK%^r-like %^WHITE%^sheen%^BLACK%^ and within "
                   "its surface it holds the most disconcerting reflection of the "
                   "%^RED%^ch%^RESET%^%^RED%^a%^BOLD%^%^RED%^ndel%^MAGENTA%^i"
                   "%^RESET%^%^RED%^e%^BOLD%^%^RED%^r%^BOLD%^%^BLACK%^. The ground "
                   "beneath the %^RED%^b%^RESET%^%^RED%^e%^BOLD%^%^RED%^j%^RESET%^"
                   "%^RED%^e%^BOLD%^%^RED%^w%^WHITE%^e%^RED%^l%^RESET%^%^RED%^e"
                   "%^BOLD%^%^RED%^d %^BLACK%^fixture looks like a pool of %^RED%^"
                   "blood %^BLACK%^that has been disturbed by a fresh dr%^RED%^o"
                   "%^BLACK%^p, progressively larger %^RESET%^%^RED%^r%^BOLD%^"
                   "%^RED%^u%^RESET%^%^RED%^by red %^BOLD%^%^BLACK%^circles "
                   "emanating from its center.%^RESET%^",
                   ({ "fireplace", "hearth", "chairs", "rug" }) : "%^BOLD%^%^BLACK%^A "
                   "large welcoming %^MAGENTA%^fireplace %^BLACK%^has been built "
                   "into the northwestern corner of the room which accommodates "
                   "both the %^RESET%^%^MAGENTA%^hearth %^BOLD%^%^BLACK%^and a "
                   "large %^RESET%^%^ORANGE%^o%^BOLD%^%^ORANGE%^i%^RESET%^"
                   "%^ORANGE%^l pa%^BOLD%^%^ORANGE%^i%^RESET%^%^ORANGE%^nting "
                   "%^BOLD%^%^BLACK%^above it. An %^RESET%^iron ribcage %^BOLD%^"
                   "%^BLACK%^rests within the pit, holding unblemished %^RESET%^"
                   "%^ORANGE%^logs %^BOLD%^%^BLACK%^that are lit with vivid "
                   "%^RESET%^%^MAGENTA%^f%^BOLD%^%^MAGENTA%^a%^WHITE%^e%^MAGENTA%^"
                   "r%^RESET%^%^MAGENTA%^ie f%^BOLD%^%^WHITE%^i%^MAGENTA%^r%^RESET%^"
                   "%^MAGENTA%^e %^BOLD%^%^BLACK%^that does not strain the eye "
                   "or cast warmth, indicating that this is a focal point more "
                   "than anything else. Indeed, the room is at a comfortable "
                   "temperature and in little need of adjustment. A %^WHITE%^"
                   "white leather cha%^RESET%^i%^BOLD%^%^WHITE%^se %^BLACK%^and "
                   "a few %^WHITE%^chairs %^BLACK%^have been scattered around "
                   "the %^MAGENTA%^fireplace %^BLACK%^and a %^RESET%^rug %^BOLD%^"
                   "%^BLACK%^made from the pelt of an animal that had soft, dark "
                   "g%^WHITE%^r%^RESET%^e%^BOLD%^%^BLACK%^y f%^RESET%^u%^BOLD%^"
                   "%^BLACK%^r.%^RESET%^",
                   ({ "paintings", "painting" }) : "%^BOLD%^%^BLACK%^Featured above "
                   "the hearth and three of the walls are large %^RESET%^%^ORANGE%^"
                   "o%^BOLD%^%^ORANGE%^i%^RESET%^%^ORANGE%^l pa%^BOLD%^%^ORANGE%^i"
                   "%^RESET%^%^ORANGE%^ntings %^BOLD%^%^BLACK%^that appear to "
                   "depict an evolving story. They can be examined individually.%^RESET%^",
                   ({ "painting 1", "first painting" }) : "%^RESET%^Hanging above the "
                   "%^MAGENTA%^f%^BOLD%^%^MAGENTA%^i%^WHITE%^r%^MAGENTA%^e%^RESET%^"
                   "%^MAGENTA%^pla%^BOLD%^%^MAGENTA%^c%^RESET%^%^MAGENTA%^e "
                   "%^WHITE%^bordered in an elaborately carved %^ORANGE%^darkwood "
                   "frame %^WHITE%^is a masterful painting depicting a beautiful "
                   "%^BOLD%^%^WHITE%^iv%^RESET%^o%^BOLD%^%^WHITE%^ry skinned "
                   "%^RESET%^elven female leading a massive %^BOLD%^%^BLACK%^obs"
                   "%^RESET%^i%^BOLD%^%^BLACK%^d%^RESET%^i%^BOLD%^%^BLACK%^an "
                   "skinned %^RESET%^male from the mouth of a %^BOLD%^%^BLACK%^cave"
                   "%^RESET%^. Lush %^GREEN%^e%^BOLD%^%^GREEN%^m%^RESET%^%^GREEN%^e"
                   "%^CYAN%^r%^GREEN%^a%^BOLD%^%^GREEN%^l%^RESET%^%^GREEN%^ds "
                   "%^WHITE%^are used to bring the %^GREEN%^forest %^WHITE%^around "
                   "them to life with %^ORANGE%^g%^BOLD%^%^ORANGE%^o%^RESET%^%^ORANGE%^"
                   "lden sh%^BOLD%^%^ORANGE%^a%^RESET%^%^ORANGE%^fts %^WHITE%^and "
                   "%^BOLD%^%^BLACK%^dark shadows d%^WHITE%^a%^RESET%^p%^BOLD%^%^WHITE%^"
                   "p%^BLACK%^l%^RESET%^i%^BOLD%^%^WHITE%^n%^BLACK%^g %^RESET%^the scene. "
                   "While the female looks up with wide %^RED%^cr%^BOLD%^%^RED%^i%^RESET%^"
                   "%^RED%^ms%^BOLD%^%^RED%^o%^RESET%^%^RED%^n e%^BOLD%^%^RED%^y%^MAGENTA%^"
                   "e%^RESET%^%^RED%^s %^WHITE%^and a joyous smile at the rays of "
                   "%^BOLD%^%^ORANGE%^light %^RESET%^cutting through the %^GREEN%^f"
                   "%^CYAN%^o%^GREEN%^l%^ORANGE%^i%^GREEN%^age %^WHITE%^the male's "
                   "face is downturned, his %^BOLD%^%^BLUE%^b%^CYAN%^l%^WHITE%^u"
                   "%^CYAN%^e %^BLUE%^e%^CYAN%^y%^WHITE%^e%^BLUE%^s %^RESET%^squinted "
                   "uncomfortably.",
                   ({ "painting 2", "second painting" }) : "%^RESET%^Hanging on the east wall "
                   "bordered in an elaborately carved %^ORANGE%^darkwood frame "
                   "%^WHITE%^is a scene depicting a group of elves conversing on the "
                   "edge of a large %^CYAN%^cr%^GREEN%^y%^CYAN%^s%^BOLD%^%^CYAN%^t"
                   "%^WHITE%^a%^CYAN%^l%^RESET%^%^CYAN%^l%^GREEN%^i%^CYAN%^ne p%^BOLD%^"
                   "%^CYAN%^o%^RESET%^%^CYAN%^nd%^WHITE%^. A tall %^BOLD%^%^WHITE%^iv"
                   "%^RESET%^o%^BOLD%^%^WHITE%^ry skinned %^RESET%^elven woman seems "
                   "to be leading the conversation, her %^BOLD%^%^RED%^r%^RESET%^"
                   "%^RED%^u%^BOLD%^%^RED%^by e%^RESET%^%^RED%^y%^BOLD%^%^MAGENTA%^e"
                   "%^RED%^s %^RESET%^sparkling while she raises her hands in wide "
                   "sweeping gestures that pull her %^BOLD%^%^BLACK%^thin robes "
                   "%^RESET%^tightly over her alluring frame. The two she speaks "
                   "to are %^ORANGE%^darker skinned sylvans%^WHITE%^, one a powerfully "
                   "built male with a %^RED%^f%^BOLD%^%^RED%^i%^RESET%^%^ORANGE%^e"
                   "%^RED%^ry m%^BOLD%^%^RED%^o%^RESET%^%^RED%^hawk %^RESET%^and the "
                   "other a lithe muscled female with rich %^ORANGE%^a%^RED%^u"
                   "%^ORANGE%^b%^RED%^u%^BOLD%^%^RED%^r%^RESET%^%^RED%^n %^ORANGE%^h"
                   "%^RED%^a%^BOLD%^%^RED%^%^RESET%^%^ORANGE%^ir %^WHITE%^and bright "
                   "%^GREEN%^em%^CYAN%^e%^GREEN%^r%^BOLD%^%^GREEN%^a%^RESET%^%^GREEN%^ld "
                   "e%^CYAN%^y%^BOLD%^%^GREEN%^e%^RESET%^%^GREEN%^s%^WHITE%^. "
                   "%^GREEN%^Trees %^WHITE%^surround them casting %^BOLD%^%^BLACK%^d"
                   "%^WHITE%^a%^RESET%^p%^BOLD%^%^BLACK%^p%^WHITE%^l%^RESET%^e%^BOLD%^"
                   "%^BLACK%^d shadows %^RESET%^across the %^CYAN%^pond %^WHITE%^and "
                   "those gathered. Peering out from behind the tree line a %^BOLD%^"
                   "%^BLACK%^dark silhouette %^RESET%^with %^BOLD%^%^CYAN%^gl%^RESET%^"
                   "%^CYAN%^a%^BOLD%^%^CYAN%^c%^WHITE%^i%^RESET%^%^CYAN%^a%^BOLD%^"
                   "%^CYAN%^l e%^RESET%^%^CYAN%^y%^BOLD%^%^CYAN%^es %^RESET%^watches the elves.",
                   ({ "painting 3", "third painting" }) : "%^RESET%^Hanging on the south "
                   "wall bordered in an elaborately carved %^ORANGE%^darkwood frame"
                   "%^RESET%^ is a scene depicting an army of %^BOLD%^%^BLACK%^dark "
                   "%^RESET%^and %^ORANGE%^sylvan elves%^WHITE%^, armed and armored "
                   "flowing from the %^GREEN%^tr%^BOLD%^%^GREEN%^e%^RESET%^%^GREEN%^es "
                   "%^WHITE%^at the large %^BOLD%^%^BLACK%^city gates%^RESET%^. %^RED%^"
                   "Human soldiers %^WHITE%^are arrayed to meet the charge but the fear "
                   "in their eyes is clearly rendered. Leading the charge is a small "
                   "group of elves bound in the finest %^BOLD%^%^CYAN%^enchanted armors "
                   "%^RESET%^and s%^BOLD%^%^WHITE%^h%^CYAN%^i%^RESET%^m%^BOLD%^%^WHITE%^m"
                   "%^CYAN%^e%^RESET%^ri%^BOLD%^%^WHITE%^n%^RESET%^g weapons. An %^BOLD%^"
                   "%^WHITE%^ivory skinned %^RESET%^female and %^BOLD%^%^BLACK%^black "
                   "skinned %^RESET%^male with bra%^BOLD%^%^WHITE%^i%^RESET%^ded and "
                   "beaded hair curl their fingers as they summon %^RED%^killing spells "
                   "%^WHITE%^while two sylvan warriors, male and female charge ahead with "
                   "bright %^ORANGE%^g%^BOLD%^%^ORANGE%^o%^RESET%^%^ORANGE%^lden bl%^BOLD%^"
                   "%^ORANGE%^a%^RESET%^%^ORANGE%^des %^WHITE%^promising %^BOLD%^%^BLACK%^"
                   "death %^RESET%^to those standing before them.",
                   ({ "painting 4", "fourth painting" }) : "%^RESET%^Hanging on the west wall "
                   "bordered by an elaborate %^ORANGE%^darkwood frame %^RESET%^is a "
                   "scene depicting hundreds of %^ORANGE%^sylvan %^RESET%^and %^BOLD%^"
                   "%^BLACK%^dark elves %^RESET%^gathered around on the %^BOLD%^%^BLACK%^"
                   "c%^RESET%^o%^BOLD%^%^BLACK%^bb%^RESET%^l%^ORANGE%^e%^BOLD%^%^BLACK%^d "
                   "bl%^RED%^o%^RESET%^%^RED%^o%^BOLD%^%^BLACK%^d st%^RED%^a%^RESET%^%^RED%^"
                   "i%^BOLD%^%^BLACK%^n%^RESET%^%^ORANGE%^e%^BOLD%^%^BLACK%^d str%^RESET%^"
                   "%^ORANGE%^e%^RED%^e%^BOLD%^%^BLACK%^ts %^RESET%^with arms and weapons "
                   "raised in %^BOLD%^%^ORANGE%^jubilation%^RESET%^. At their center "
                   "stands the %^BOLD%^%^WHITE%^iv%^RESET%^o%^BOLD%^%^WHITE%^ry skinned "
                   "gh%^RESET%^o%^BOLD%^%^WHITE%^st %^RESET%^of an elf with her arms held "
                   "wide addressing the crowd. She is flanked by a massive %^BOLD%^%^BLACK%^"
                   "obs%^RESET%^i%^BOLD%^%^BLACK%^di%^RESET%^a%^BOLD%^%^BLACK%^n skinned "
                   "%^RESET%^male wielding a %^BOLD%^%^BLACK%^w%^BLUE%^i%^BLACK%^ck%^CYAN%^e"
                   "%^BLACK%^d %^RESET%^looking %^BOLD%^%^BLACK%^spear %^RESET%^and a "
                   "smaller%^BOLD%^%^WHITE%^ b%^BLACK%^e%^RED%^a%^WHITE%^ded %^RESET%^and "
                   "%^BOLD%^%^WHITE%^braided %^RESET%^male who looks on the crowd with "
                   "pride. Standing close to the smaller male is a female sylvan with "
                   "%^RED%^a%^ORANGE%^u%^RED%^bu%^BOLD%^%^RED%^r%^RESET%^%^RED%^n "
                   "h%^ORANGE%^a%^BOLD%^%^RED%^i%^RESET%^%^RED%^r %^WHITE%^and an "
                   "enchanting smile while at her side a well-muscled sylvan with a "
                   "%^RED%^f%^BOLD%^%^RED%^i%^RESET%^%^RED%^ery m%^BOLD%^%^RED%^o%^RESET%^"
                   "%^RED%^hawk %^WHITE%^stands attentively. High overhead the %^BOLD%^"
                   "%^BLACK%^silhouette %^RESET%^of a dragon flies off into the distance.",
                   "chandelier" : "%^BOLD%^%^BLACK%^A six tiered chandelier, each of its "
                   "circular levels smaller than the last, hangs from the ceiling. "
                   "Delicate %^RED%^r%^RESET%^%^RED%^u%^BOLD%^%^RED%^by str%^RESET%^"
                   "%^RED%^a%^BOLD%^%^RED%^nds %^BLACK%^hang from the slender metal "
                   "circles, the %^WHITE%^wet%^BLACK%^-looking stones cut to a %^RESET%^"
                   "%^CYAN%^t%^GREEN%^e%^BOLD%^%^CYAN%^a%^RESET%^%^CYAN%^r%^BOLD%^%^BLACK%^"
                   "-drop shape that resembles beads of %^RESET%^%^RED%^bl%^BOLD%^"
                   "%^RED%^oo%^RESET%^%^RED%^d%^BOLD%^%^BLACK%^. The %^RESET%^%^RED%^"
                   "gemstones %^BOLD%^%^BLACK%^cast a warm %^RESET%^%^RED%^cr%^BOLD%^"
                   "%^RED%^i%^RESET%^%^RED%^ms%^BOLD%^%^RED%^o%^RESET%^%^RED%^n l%^BOLD%^"
                   "%^RED%^i%^WHITE%^g%^RESET%^%^RED%^ht %^BOLD%^%^BLACK%^across the room.%^RESET%^",
                   ({ "stairs", "staircase", "stairwell" }) : "%^BOLD%^%^BLACK%^A skilled "
                   "artisan has crafted this magnificent %^RESET%^%^ORANGE%^darkwood "
                   "staircase%^BOLD%^%^BLACK%^, sanded the wood smooth and buffed it, "
                   "giving it a %^WHITE%^glossy %^BLACK%^finish. The staircase widens "
                   "at the bottom and becomes narrower as it ascends. The %^RESET%^"
                   "%^ORANGE%^bannisters %^BOLD%^%^BLACK%^at the base have been carved "
                   "to resemble seated dragons with their wings pinned against their ribs. "
                   "A %^RED%^red%^BLACK%^, plush carpet %^RESET%^%^ORANGE%^r%^RED%^u%^BOLD%^"
                   "%^RED%^nn%^RESET%^%^RED%^e%^ORANGE%^r %^BOLD%^%^BLACK%^protects the "
                   "stairs from %^RESET%^scuffing%^BOLD%^%^BLACK%^. On the lower right "
                   "hand side an inconspicuous archway interrupts the %^RESET%^%^ORANGE%^"
                   "wood paneling %^BOLD%^%^BLACK%^and leads to a narrow, %^RESET%^"
                   "darkened stairwell%^BOLD%^%^BLACK%^.%^RESET%^",
                   ({ "walls", "wall", "panels", "paneling" }) : "%^BOLD%^%^BLACK%^The walls "
                   "are lined with rich %^RESET%^%^ORANGE%^darkwood panels %^BOLD%^"
                   "%^BLACK%^ that insulate the room, keeping it at a comfortable "
                   "temperature and reducing reverberation.%^RESET%^",
                   "ceiling" : "%^BOLD%^%^WHITE%^Made from the same material as the "
                   "pillars the arched ceiling is composed of pale dr%^RESET%^a"
                   "%^BOLD%^%^WHITE%^gon bone scr%^RESET%^i%^BOLD%^%^WHITE%^msh"
                   "%^ORANGE%^a%^WHITE%^w. It has been treated so that its color "
                   "is a pristine i%^RESET%^v%^BOLD%^%^ORANGE%^o%^RESET%^r%^BOLD%^"
                   "%^WHITE%^y and there is no residual %^MAGENTA%^tissue %^WHITE%^"
                   "but the natural texture remains, the bone like thick w%^BLACK%^e"
                   "%^WHITE%^bb%^RESET%^i%^BOLD%^%^WHITE%^ng in some places and "
                   "completely s%^ORANGE%^o%^WHITE%^lid in others.%^RESET%^"
               ]));
    set_exits(([
                   "west" : ROOMS "west_wing",
                   "down" : ROOMS "downward_spiral",
                   "stairs" : ROOMS "upper_landing",
                   "south" : ROOMS "dragons_landing"
               ]));
    set_door("palace doors", ROOMS "dragons_landing", "south", "aunuit_key_xyz", "runes"); //There is no key
    set_open("palace doors", 0);
    set_locked("palace doors", 1, "lock");
    lock_difficulty("palace doors",  "/daemon/player_housing"->get_phouse_lock_dc("legendary"), "lock");
    set_door_description("palace doors", "%^BOLD%^%^BLACK%^The entryway of "
                         "the palace is somewhat like entering the %^RED%^maw %^BLACK%^of a "
                         "giant b%^RESET%^%^RED%^e%^BOLD%^%^BLACK%^ast with the doors resting "
                         "at the end of a hall beneath the subsequent floors of the structure. "
                         "The beautiful %^RESET%^%^ORANGE%^darkwood doors %^BOLD%^%^BLACK%^are edged with delicate scr%^RESET%^o%^BOLD%^"
                         "%^BLACK%^llw%^WHITE%^o%^RESET%^r%^BOLD%^%^BLACK%^k that has been carved "
                         "around the perimeter of the doors and filled with a %^RESET%^s%^BOLD%^"
                         "%^WHITE%^i%^CYAN%^l%^BLACK%^v%^WHITE%^e%^RESET%^r metal %^BOLD%^"
                         "%^BLACK%^that causes them to appear %^WHITE%^luminescent%^BLACK%^. "
                         "The surface of the rich %^RESET%^%^ORANGE%^wood %^BOLD%^%^BLACK%^gleams "
                         "from constant polishing and s%^WHITE%^e%^BLACK%^rpe%^WHITE%^n%^BLACK%^"
                         "t%^RESET%^i%^BOLD%^%^BLACK%^ne ad%^WHITE%^a%^BLACK%^mant%^RESET%^i"
                         "%^BOLD%^%^BLACK%^um %^RESET%^handles %^BOLD%^%^BLACK%^have been "
                         "crafted for each of the %^RESET%^%^ORANGE%^double doors %^BOLD%^"
                         "%^BLACK%^but vigilant %^BLUE%^guards %^BLACK%^patrolling the length "
                         "of the entryway indicate that access to the palace is not a simple thing.%^RESET%^");
}
