#include <std.h>
inherit WIZ;

void create() {
        ::create();
        set_property("indoors",1);  // is 0 if outdoors
        set_property("light",4);    // Pretty Bright for a library? People need to see? I dont want it hugely bright, but decent 
        set_terrain(WIZ);
        set_travel(WIZ);
        set_name(" Multi-tiered Library ");    // should be the same as the set_short but without
colors
        set_short("%^RESET%^%^RED%^ Multi-tiered %^BOLD%^%^BLACK%^L%^RESET%^%^MAGENTA%^i%^BOLD%^%^BLACK%^brary%^RESET%^"); 
        set_long(%^RESET%^%^RED%^The walls of this multi-tiered chamber are composed of %^BOLD%^%^WHITE%^s%^CYAN%^i%^WHITE%^lv%^CYAN%^e%^WHITE%^r ve%^CYAN%^i%^WHITE%^ned marble%^RESET%^%^RED%^ with a %^BOLD%^%^YELLOW%^magn%^CYAN%^i%^YELLOW%^f%^CYAN%^i%^YELLOW%^cent%^RESET%^%^RED%^ vaulted ceiling supported by several solid columns. An %^MAGENTA%^e%^BOLD%^%^MAGENTA%^rr%^RESET%^%^MAGENTA%^atic%^RESET%^%^RED%^ maze of bookshelves can be seen on each level of the three tiered chamber leaving an %^BOLD%^%^BLACK%^ov%^GREEN%^e%^BLACK%^rwh%^GREEN%^e%^BLACK%^lming%^RESET%^%^RED%^ feeling from the sheer size and scale of this structure. Many %^BOLD%^%^CYAN%^g%^WHITE%^l%^CYAN%^ass%^RESET%^%^RED%^ display c%^BOLD%^%^MAGENTA%^a%^RESET%^%^RED%^ses housing %^MAGENTA%^e%^BOLD%^%^MAGENTA%^x%^RESET%^%^MAGENTA%^otic %^CYAN%^artifacts%^RESET%^%^RED%^ are located on the first tier along with a large %^ORANGE%^oak%^RESET%^%^RED%^ desk. Hanging above the desk is a masterfully-crafted woven image of a  %^BOLD%^%^RED%^dra%^WHITE%^c%^RED%^oli%^WHITE%^c%^RED%^h%^RESET%^%^RED%^. Several smaller desks are scattered about each tier giving the occupants a comfortable reading area. The middle tier contains vast amounts of bookshelves, chaotically placed %^BOLD%^%^WHITE%^sc%^RESET%^u%^BOLD%^%^WHITE%^lpt%^RESET%^u%^BOLD%^%^WHITE%^res%^RESET%^%^RED%^ and %^BOLD%^%^GREEN%^pa%^RESET%^%^GREEN%^i%^BOLD%^%^GREEN%^nt%^RESET%^%^GREEN%^i%^BOLD%^%^GREEN%^ngs%^RESET%^%^RED%^ strewn about its maze. The last tier is smaller than the other two with its maze being even more %^MAGENTA%^h%^BOLD%^%^MAGENTA%^e%^RESET%^%^MAGENTA%^ctic%^RESET%^%^RED%^ than the others, but that could be an %^BOLD%^%^WHITE%^i%^CYAN%^l%^WHITE%^lus%^CYAN%^i%^WHITE%^on%^RESET%^%^RED%^ of the %^BOLD%^%^BLUE%^eye%^RESET%^%^RED%^ from this great distance. A massive %^MAGENTA%^f%^BOLD%^%^MAGENTA%^r%^WHITE%^e%^MAGENTA%^sc%^RESET%^%^MAGENTA%^o%^RED%^ of a %^BOLD%^%^BLACK%^jaw%^RED%^l%^BLACK%^ess sk%^RED%^u%^BLACK%^ll%^RESET%^%^RED%^ against a chaotic vi%^BOLD%^%^MAGENTA%^o%^RESET%^%^RED%^let %^RESET%^%^MAGENTA%^sunburst%^RESET%^%^RED%^ seems to stare down from the vaulted ceiling, filling you with a feeling of %^BOLD%^%^BLACK%^ens%^WHITE%^l%^BLACK%^avement%^RESET%^%^RED%^ and %^BOLD%^%^BLACK%^op%^GREEN%^p%^BLACK%^res%^GREEN%^s%^BLACK%^ion%^RESET%^%^RED%^ despite the immaculately %^CYAN%^clean%^RED%^ and well organized nature of this library. %^RESET%^
");
        set_smell("default","%^RESET%^ORANGE%^The smell of old tomes and mil dewed paper fills the chamber. %^RESET%^    ");
        set_listen("default","%^RESET%^%^GREEN%^An unnatural silence fills the air sending a chill down your spine. %^RESET%^ ");
// These are the things you can look at.  If you want more than one word or
words (oil lamp and lamp, chair and chairs) to work, all the words you want
to see the same thing go in the ({ }) like chair & chairs below.
        set_items(([
           ({"walls","marble walls"}) : %^RESET%^%^RED%^Your %^RESET%^reflection%^RED%^ stares back at you from the %^BOLD%^%^WHITE%^glossy%^RESET%^%^RED%^ finish of the most expensive and highest grade marble %^BOLD%^%^YELLOW%^gold%^RESET%^%^RED%^ can buy. The image is slightly distorted by the %^BOLD%^%^WHITE%^ve%^CYAN%^i%^WHITE%^ns%^RESET%^%^RED%^ of %^BOLD%^%^WHITE%^s%^CYAN%^i%^WHITE%^l%^CYAN%^v%^WHITE%^er%^RESET%^%^RED%^ flowing throughout the marble walls. %^RESET%^",
           ({"bookshelves"}) : %^RESET%^%^RED%^ Numerous %^ORANGE%^bookshelves%^RED%^ are spread about %^MAGENTA%^e%^BOLD%^%^MAGENTA%^rr%^RESET%^%^MAGENTA%^atically%^RED%^ about the chamber. The %^BOLD%^%^BLACK%^books%^RESET%^%^RED%^ themselves, however, seem well organized with some unknown, %^BOLD%^%^BLACK%^ch%^CYAN%^a%^BLACK%^otic%^RESET%^%^RED%^ method of organization.%^RESET%^",
	
({"columns","ceiling"}) : -%^RESET%^%^RED%^Enormous marble columns decorated with woven tapestries support the ceiling of this massive chamber which must rise at least 30 feet above your head. %^RESET%^",
	({"display cases","cases",artifactsl}) : %^RESET%^%^RED%^Fine glass cases of violet tint house numerous artifacts of immense power and prestige. Your attention is drawn to three cases in particular which prominentlydisplay a %^MAGENTA%^dagger%^RESET%^%^RED%^, asword %^BOLD%^%^RED%^replica%^RESET%^%^RED%^, and shattered fragments of a large %^BOLD%^%^YELLOW%^blade%^RESET%^%^RED%^.%^RESET%^
	
({"dagger"}) :  %^RESET%^%^BLUE%^This dagger is north short of a work of %^BOLD%^%^BLUE%^art%^RESET%^%^BLUE%^. Elaborate designs wrap their way up its %^BOLD%^%^BLACK%^obs%^RESET%^%^ORANGE%^i%^BOLD%^%^BLACK%^d%^RESET%^%^ORANGE%^i%^BOLD%^%^BLACK%^an h%^RESET%^%^i%^BOLD%^%^BLACK%^lt%^RESET%^%^BLUE%^, marking out %^RESET%^%^MAGENTA%^da%^CYAN%^rk%^MAGENTA%^ly%^RESET%^%^BLUE%^-%^MAGENTA%^gl%^CYAN%^owi%^MAGENTA%^ng%^RESET%^%^BLUE%^, abstract patterns against the blackended grip. They draw the eye upward, past the swept hilt towards its %^RESET%^gl%^BOLD%^%^BLACK%^a%^RESET%^ssy bl%^BOLD%^%^BLACK%^a%^RESET%^de%^BLUE%^ which, despite  its smooth surface, reflects no %^BOLD%^%^YELLOW%^l%^WHITE%^i%^YELLOW%^g%^WHITE%^h%^YELLOW%^t%^RESET%^%^BLUE%^ forth. The blade itself is absolutely flawless, marred only by the detailed %^GREEN%^r%^BOLD%^%^GREEN%^u%^RESET%^%^GREEN%^n%^BOLD%^%^GREEN%^e%^RESET%^%^GREEN%^s%^BLUE%^ that mark out unknown meaning across its surface. They glow %^MAGENTA%^so%^CYAN%^ft%^MAGENTA%^ly%^BLUE%^ with a faded gleam, creating a beautiful contrast with the weapon's oddly %^BOLD%^%^BLACK%^in%^RESET%^s%^BOLD%^%^BLACK%^ubs%^RESET%^t%^BOLD%^%^BLACK%^ant%^RESET%^i%^BOLD%^%^BLACK%^al%^RESET%^%^BLUE%^, and you can often catch a glimpses right through its wavering form. %^RESET%^%^MAGENTA%^A %^ORANGE%^plaque%^MAGENTA%^ on the display case reads: %^BOLD%^%^BLACK%^Sh%^RESET%^%^BLUE%^e%^BOLD%^%^BLACK%^ol Dag%^RESET%^%^MAGENTA%^g%^BOLD%^%^BLACK%^ger%^RESET%^%^MAGENTA%^ donated by %^BOLD%^%^WHITE%^The Family. %^RESET%^
.",

({"replica"}) : %^BOLD%^%^BLACK%^This long twisted blade is made from a black, unknown metal, both light-weight and durable. The double-edge blade is %^RED%^razor-sharp%^BLACK%^, barbed and serrated in some parts, smooth and fine edged in others - a blade of %^GREEN%^chaos%^BLACK%^. A deep %^RED%^blood%^BLACK%^groove travels along the length of the blade, flanked on either side by jagged %^CYAN%^runes%^BLACK%^. THere is a sense of wrongness about the %^CYAN%^runes%^BLACK%^, to look on them is to feel uneasy. The hilt is carved from soft black stone, wrapped in suplle leather of some unknown beast. A thick %^RED%^blood-ruby%^BLACK%^ has been set into the end of the hilt, secured firmly by a set of black claws. %^BOLD%^%^WHITE%^A plaque on the display case reads: Replica of %^BLACK%^E%^RESET%^%^RED%^d%^BOLD%^%^BLACK%^ge of %^RESET%^%^RED%^D%^BOLD%^%^RED%^i%^RESET%^%^RED%^s%^BOLD%^%^RED%^c%^RESET%^%^RED%^o%^BOLD%^%^RED%^r%^RESET%^%^RED%^d%^BOLD%^%^WHITE%^.%^RESET%^
.",

({"sword",shattered sword}) :  %^BOLD%^%^BLACK%^Quickly you realize it isn't just one shattered sword displayed within the case, but two. Two %^CYAN%^sparkling %^RESET%^%^RED%^r%^BOLD%^%^RED%^u%^RESET%^%^RED%^b%^BOLD%^%^RED%^i%^RESET%^%^RED%^e%^BOLD%^%^RED%^s%^BLACK%^ lay unattached from the hilts within which they were once set. The %^RED%^star ruby%^BOLD%^%^BLACK%^ is missing two of its points and is badly blemished from what had to be a horrible blast of n%^RESET%^%^MAGENTA%^e%^BOLD%^%^BLACK%^g%^RESET%^%^MAGENTA%^a%^BOLD%^%^BLACK%^t%^RESET%^%^MAGENTA%^i%^BOLD%^%^BLACK%^v%^RESET%^%^MAGENTA%^e%^BOLD%^%^RED%^ energy%^BLACK%^ or u%^GREEN%^n%^BLACK%^h%^GREEN%^o%^BLACK%^ly %^WHITE%^might%^BLACK%^. The other %^RESET%^%^RED%^ruby%^BOLD%^%^BLACK%^ seems to have endured the same fate as it contains a deep %^RESET%^%^CYAN%^crack%^BOLD%^%^BLACK%^ in its center.  The blades of these two promising swords seemed to have once %^BOLD%^%^YELLOW%^glowed%^BLACK%^ with powerful %^YELLOW%^light%^BLACK%^ only to be dimed by a %^RESET%^%^MAGENTA%^hazy %^BOLD%^%^BLACK%^d%^WHITE%^a%^BLACK%^rkn%^WHITE%^e%^BLACK%^ss that surrounds both edges of these once %^WHITE%^holy%^BLACK%^ relics. A plaque on the display case reads:  %^RESET%^%^MAGENTA%^Some Darkness not even the purest of %^ORANGE%^light%^MAGENTA%^ can %^BOLD%^%^YELLOW%^lighten%^RESET%^%^MAGENTA%^.%^RESET%^",

{"oak desk","desk"}) : %^RESET%^%^RED%^A large, circular %^ORANGE%^oak%^RED%^ desk its in the center of the room. Papers, office supplies, and reading material are scattered haphazardly about the desk. %^RESET%^",
({"tapestries","dracolich tapestry","image", "woven image"}) : %^RESET%^%^RED%^Scattered across the library are %^MAGENTA%^t%^BOLD%^%^MAGENTA%^a%^RESET%^%^MAGENTA%^pest%^BOLD%^%^MAGENTA%^r%^RESET%^%^MAGENTA%^ies%^RESET%^%^RED%^ of various forms of %^RESET%^undead%^RED%^, %^BOLD%^%^BLACK%^nightmares%^RESET%^%^RED%^, and other Cyricist associated creatures. However, one large tapestry in particular hanging above the %^ORANGE%^oak%^RED%^ desk draws your immediate attention. A massive %^BOLD%^%^RED%^dra%^WHITE%^c%^RED%^oli%^WHITE%^c%^RED%^h%^RESET%^%^RED%^ with its %^BOLD%^%^GREEN%^ra%^RESET%^%^GREEN%^gg%^BOLD%^%^GREEN%^ed%^RESET%^%^RED%^ wings outspread soaring through the air with something clutched in its %^RESET%^bony %^BOLD%^%^BLACK%^talon%^RESET%^%^RED%^. As you stare at the object within the undead dragon's talon it dawns upon you that it could be a %^BOLD%^%^CYAN%^sparrow%^RESET%^%^RED%^ or %^BOLD%^%^MAGENTA%^butterfly%^RESET%^%^RED%^ perhapsbut that could just be a trick of the %^BOLD%^%^RED%^eye%^RESET%^%^RED%^!%^RESET%^",

({"sculptures"}) : %^RESET%^%^RED%^A few dozen %^CYAN%^masterfully-crafted%^RED%^ %^BOLD%^%^WHITE%^sc%^RESET%^u%^BOLD%^%^WHITE%^lpt%^RESET%^u%^BOLD%^%^WHITE%^res%^RESET%^%^RED%^ are scattered about the second floor of this chamber. A few catch your eye, but one directly in the center of the second fully draws you in. It is a life-sized replica of three life-like beings. On the left is a massive half-ogre drinking something out of a decorated %^BOLD%^%^CYAN%^decanter%^RESET%^%^RED%^. Next to him is a black haired human man with a %^BOLD%^%^BLACK%^holy %^WHITE%^symbol%^RESET%^%^RED%^ around his neck and a stunningly beautiful half-elf woman leaning against the human mans right shoulder, her hands calmly resting on the hilt of her %^BOLD%^%^RED%^blades%^RESET%^%^RED%^.  A plaque is at the bottom of this sculpture.)( %^BOLD%^%^BLACK%^The Plaque reads The %^RESET%^%^MAGENTA%^Family%^BOLD%^%^BLACK%^- Krusk, Alzar and Dorje united in %^BOLD%^%^RED%^mu%^WHITE%^r%^RED%^der%^BLACK%^ and %^BOLD%^%^BLACK%^m%^GREEN%^a%^BLACK%^dness.%^RESET%^",

({"paintings"}) : %^RESET%^%^RED%^Detailed %^BOLD%^%^GREEN%^pa%^RESET%^%^GREEN%^i%^BOLD%^%^GREEN%^nt%^RESET%^%^GREEN%^i%^BOLD%^%^GREEN%^ngs%^RESET%^%^RED%^ of prominent %^BOLD%^%^WHITE%^Cyricist%^RESET%^%^RED%^ are scattered about the library. Not a single painting seems to give great details to the figures, but a few names are listed below each painting. An empty %^BOLD%^%^WHITE%^slot%^RESET%^%^RED%^ for a painting rest near the back of the second floor below it is a large cloth draping what appears to be a painting that was never hung. Perhaps you could %^BOLD%^%^CYAN%^remove%^RESET%^%^RED%^ the cloth.%^RESET%^",
({"fresco"}) : "%^RESET%^%^%^RED%^The center of the vaulted ceiling has a massive %^MAGENTA%^f%^BOLD%^%^MAGENTA%^r%^WHITE%^e%^MAGENTA%^sc%^RESET%^%^MAGENTA%^o%^RED%^ of a %^BOLD%^%^BLACK%^jaw%^RED%^l%^BLACK%^ess sk%^RED%^u%^BLACK%^ll%^RESET%^%^RED%^. The empty %^BOLD%^%^BLACK%^eye-%^WHITE%^socket's%^RESET%^%^RED%^ of the skull seem to %^BOLD%^%^RED%^blaze%^RESET%^%^RED%^ with vi%^BOLD%^%^MAGENTA%^o%^RESET%^%^RED%^let light as it stares down on the occupants of the library leaving one with a deep feeling of complete %^BOLD%^%^BLACK%^ens%^WHITE%^l%^BLACK%^avement%^RESET%^%^RED%^ and utter pow%^BOLD%^%^RED%^e%^RESET%^%^RED%^rl%^BOLD%^%^RED%^e%^RESET%^ssn%^BOLD%^%^RED%^e%^RESET%^%^RED%^ss. %^RESET%^",


           ({"   ", "  " }) : "    ",
        ]));
// For exits, just give us the directions (which can be enter, down, living
room, or whatever as well as north/south type directions.  Also put the
name (or short description) of the room they go to where I have filename,
we'll assign the actual filenames but that will help us keep track of how
you intend for things to connect.
        set_exits(([
           "east" : "WIZ (filename)",
        ]));
// if you want doors and there is more than one, they have to be unique, so
specify a color, wood type, or something.  Note:  all doors need an exit,
so even though you define the door here, you also have to include the exit
in set_exits above.
        set_door("%^ORANGE%^Large Oak Doors%^RESET%^","WIZ (filename)","south",0);
        set_door_description("%^RESET%^%^ORANGE%^Luxurious oak double doors stand at the entrance to this multi-tiered chamber. The doors were constructed out of the highest quality oak and treated with some unknown %^MAGENTA%^substance%^ORANGE%^ to strengthen them and add a high-gloss %^BOLD%^%^YELLOW%^shine%^RESET%^%^ORANGE%^. Each door has a detailed image of %^BOLD%^%^WHITE%^undead creatures%^RESET%^%^ORANGE%^ in %^BOLD%^%^RED%^gruesome scenes%^RESET%^%^ORANGE%^ of %^RED%^carnage%^ORANGE%^ engraved upon their surface. The door handles are a black opal shaped into the form of a %^BOLD%^%^BLACK%^nightmare%^RESET%^%^ORANGE%^.%^RESET%^", "   ");
}
- - and that's the end of what goes into the very basics of a room

--More-- (93%)
If you want a key, give us a description for the key and some idea of how
it's going to be hidden and how you'll get it, etc.  Also make sure the
room has some indication of the item it's hidden in/behind, or whatever
that can be looked at.  Generally we'll want keys to fit all doors within a
house/shop.

Traps and other special room effects as well as guards and mobs are the
most time consuming for wizzes, but also add more to what the rooms
contribute to the game.  If you want guards or it's a shop and you need
clerks, etc. we'll also appreciate descriptions for them as well as race
and alignment for starters.  How far we go after that depends on time
available and suitability/balance.
->
Echo for when removing the cloth from painting!
%^BOLD%^%^WHITE%^You remove the cloth to find a painting like none you have ever seen before. The %^BOLD%^%^GREEN%^pa%^RESET%^%^GREEN%^i%^BOLD%^%^GREEN%^nt%^RESET%^%^GREEN%^i%^BOLD%^%^GREEN%^ngs%^BOLD%^%^WHITE%^ is almost life-like and seems to have been collected from the memory of someone. The image seems to focus on a %^MAGENTA%^beautiful%^WHITE%^ winged woman instead of her two companions, a %^BOLD%^%^WHITE%^cool %^BOLD%^%^BLACK%^gr%^RED%^a%^BLACK%^y%^WHITE%^-eyed male human and a %^WHITE%^pl%^RESET%^a%^BOLD%^%^WHITE%^ti%^RESET%^n%^BOLD%^%^WHITE%^um%^WHITE%^ blonde half-elf, as they walk through a library. The %^BOLD%^%^CYAN%^winged woman%^WHITE%^ is %^MAGENTA%^breathtaking%^WHITE%^ with long flowing %^BLUE%^b%^RESET%^%^BLUE%^l%^BOLD%^%^BLUE%^u%^RESET%^%^BLUE%^e %^BOLD%^%^BLUE%^l%^RESET%^%^BLUE%^o%^BOLD%^%^BLUE%^c%^RESET%^%^BLUE%^k%^BOLD%^%^BLUE%^s%^WHITE%^ and %^MAGENTA%^moist%^WHITE%^, %^CYAN%^glistening%^WHITE%^ lips. She walks about the library instructing cloaked figures sternly on their duties and organization within the chamber. The painting shifts from the library scene to a grotto filled with pillows you can see the same three figures curled up together quietly discussing matters and quite enjoying each others company. A few moments later a %^RESET%^%^ORANGE%^heavily armed half-ogre%^BOLD%^%^WHITE%^ enters with the four of them departing for adventure. A plaque has been attached at the bottom of the painting which reads: %^BOLD%^%^YELLOW%^A gift for Mistress Amarina- Keeper of %^BLACK%^Lord Cyric's%^YELLOW%^ knowledge and %^WHITE%^Mother%^YELLOW%^ of %^RESET%^%^MAGENTA%^Family Kozcha%^BOLD%^%^WHITE%^.%^RESET%^
Echos
%^RESET%^%^MAGENTA%^A %^BOLD%^%^BLACK%^cl%^RESET%^o%^BOLD%^%^BLACK%^ak%^RESET%^e%^BOLD%^%^BLACK%^d%^RESET%^%^MAGENTA%^ figure organizes books on a shelf. %^RESET%^
%^BOLD%^%^BLACK%^Various hushed voices %^BOLD%^%^WHITE%^whisper%^BLACK%^ indiscernibly throughout the library. %^RESET%^
%^BOLD%^%^RED%^The %^RESET%^%^MAGENTA%^crinkling%^BOLD%^%^RED%^ of %^WHITE%^paper%^RED%^ echoes through the %^GREEN%^eerily%^RED%^ quiet chamber. %^RESET%^
%^RESET%^%^MAGENTA%^A %^BOLD%^%^BLACK%^sh%^CYAN%^a%^BLACK%^d%^CYAN%^o%^BLACK%^wy%^RESET%^%^MAGENTA%^ figure brushes past you with little regard for your well-being. %^RESET%^