#define SHWEAP "/d/shadow/obj/weapon/"
#define SHARM "/d/shadow/obj/armor/"
#define DNROOMS "/d/newbie/rooms/drow/rooms/"
#define DNOBJ "/d/newbie/rooms/drow/obj/"
#define DNMONS  "/d/newbie/rooms/drow/mon/"
#define PASSAGE "/d/newbie/rooms/drow/passage.c"
#define CAVERN "/d/newbie/rooms/drow/cavern.c"
#define ALCOVE "/d/newbie/rooms/drow/alcove.c"
#define OUT "/d/newbie/rooms/road/froad17"
#define MONST FOREST"mon/"+
#define STUFF FOREST"stuff/"+