#define JOURNEY ([\
"/d/shadow/room/city/forkroad":"west",\
"/d/shadow/room/city/sroad":"south",\
"/d/shadow/room/city/smroad":"south",\
"/d/shadow/room/city/mroad":"south",\
"/d/guilds/fist/hall/guild1":"west",\
"/d/shadow/room/city/nroad":"south",\
"/d/shadow/room/city/tb_rd_tb":"south",\
"/d/shadow/room/city/troopb1":"west",\
"/d/shadow/room/city/troopb2":"east",\
"/d/shadow/room/city/th_rd_sc":"south",\
"/d/shadow/room/city/townhall":"west",\
"/d/shadow/room/city/scribe":"east",\
"/d/shadow/room/city/ch_rd_mu":"south",\
"/d/shadow/room/city/healer":"west",\
"/d/shadow/room/city/cguild/paladin/wood":"east",\
"/d/shadow/room/city/cguild/paladin/fountain":"east",\
"/d/shadow/room/city/al_rd_ag":"south",\
"/d/shadow/room/city/alchemist":"west",\
"/d/shadow/room/city/adventure":"east",\
"/d/shadow/room/city/gs_rd_bk":"south",\
"/d/shadow/room/city/bank":"west",\
"/d/shadow/room/city/gs_store":"east",\
"/d/shadowgate/adv_main":"southeast",\
"/d/shadowgate/ombud_hall":"up",\
"/d/shadowgate/abyss":"portal",\
"/d/shadowgate/arch/2nd_floor":"down",\
"/d/shadow/room/main/garrison5":"southeast",\
"/d/shadow/room/city/cguild/fighter/ac_fighter":"west",\
"/d/shadow/room/city/cguild/fighter/fighter":"out",\
"/d/shadow/room/main/garrison4":"south",\
"/d/shadow/room/city/library":"east",\
"/d/shadow/room/main/garrison3":"south",\
"/d/shadow/room/city/hotel":"west",\
"/d/shadow/room/main/garrison2":"south",\
"/d/shadow/room/city/troopb4":"east",\
"/d/shadow/room/main/garrison1":"south",\
"/d/shadow/room/city/troopb3":"west",\
"/d/shadow/room/main/northcross":"south",\
"/d/shadow/room/main/northgate":"south",\
"/d/shadow/room/main/northgate":"south",\
"/d/shadow/room/city/eroad1":"west",\
"/d/shadow/room/city/eroad2":"southeast",\
"/d/shadow/room/city/eroad3":"southeast",\
"/d/shadow/room/city/weapon":"west",\
"/d/shadow/room/city/eroad4":"south",\
"/d/shadow/room/city/eroad5":"south",\
"/d/shadow/room/city/egeroad":"south",\
"/d/shadow/room/city/eroad6":"south",\
"/d/shadow/room/city/eroad7":"south",\
"/d/shadow/room/city/eroad8":"south",\
"/d/shadow/room/city/eroad9":"south",\
"/d/shadow/room/city/eroad10":"south",\
"/d/shadow/room/city/eroad11":"south",\
"/d/shadow/room/city/eroad12":"south",\
"/d/shadow/room/city/eroad13":"south",\
"/d/shadow/room/city/eroad14":"south",\
"/d/shadow/room/city/eroad15":"south",\
"/d/shadow/room/city/eroad16":"south",\
"/d/shadow/room/city/eroad16":"southwest",\
"/d/shadow/room/city/druids/park1":"west",\
"/d/shadow/room/city/druids/park1_2":"west",\
"/d/shadow/room/city/druids/park2":"north",\
"/d/shadow/room/city/eroad17":"southwest",\
"/d/shadow/room/city/eroad18":"southwest",\
"/d/shadow/room/city/eroad19":"southwest",\
"/d/shadow/room/city/wroad19":"southeast",\
"/d/shadow/room/city/wroad18":"southeast",\
"/d/shadow/room/city/wroad17":"southeast",\
"/d/shadow/room/city/wroad16":"southeast",\
"/d/shadow/room/city/cguild/thief/warehouse":"east",\
"/d/shadow/room/city/wroad15":"south",\
"/d/shadow/room/city/wroad14":"south",\
"/d/shadow/room/city/wroad13":"south",\
"/d/shadow/room/city/wroad12":"south",\
"/d/shadow/room/city/church":"west",\
"/d/shadow/room/city/wroad11":"south",\
"/d/shadow/room/city/wroad10":"south",\
"/d/shadow/room/city/wroad9":"south",\
"/d/shadow/room/city/cguild/antipaladin/anti1":"east",\
"/d/shadow/room/city/cguild/antipaladin/anti2":"east",\
"/d/shadow/room/city/wroad8":"south",\
"/d/shadow/room/city/wroad7":"south",\
"/d/shadow/room/city/wroad6":"south",\
"/d/shadow/room/city/wgwroad":"south",\
"/d/shadow/room/city/wroad5":"south",\
"/d/shadow/room/city/wroad4":"south",\
"/d/shadow/room/city/wroad3":"southwest",\
"/d/shadow/room/city/armor":"east",\
"/d/shadow/room/city/wroad2":"southwest",\
"/d/shadow/room/city/wroad1":"east",\
"/d/shadow/room/city/wgroad2":"east",\
"/d/shadow/room/city/wgroad1":"east",\
"/d/shadow/room/city/westgate":"east",\
"/d/shadow/room/city/wltower":"north",\
"/d/shadow/room/city/wnltower":"south",\
"/d/shadow/room/city/innroad1":"northwest",\
"/d/shadow/room/city/innroad2":"northwest",\
"/d/shadow/room/city/inn":"northwest",\
"/d/shadow/room/city/stable":"south",\
"/d/shadow/room/city/cguild/cavalier/guild1":"out",\
"/d/shadow/room/city/egroad2":"west",\
"/d/shadow/room/city/bounty":"north",\
"/d/shadow/room/city/moffice":"west",\
"/d/shadow/room/city/egroad1":"west",\
"/d/shadow/room/city/eastgate":"west",\
"/d/shadow/room/city/barroad1":"northeast",\
"/d/shadow/room/city/barroad2":"northeast",\
"/d/shadow/room/city/bar":"northeast",\
"/d/shadow/room/city/enltower":"south",\
"/d/shadow/room/city/eltower":"north",\
])
