#define RATPATHS "/d/shadow/ratpaths/inherits/rp_inherit"
#define RATPATHS_EXIT "/d/shadow/ratpaths/inherits/rp_exit_inherit"
#define DEEPROAD "/d/shadow/ratpaths/inherits/dr_inherit"
#define DEEPROAD_TR "/d/shadow/ratpaths/inherits/dr_transition"
#define PATH "/d/shadow/ratpaths/rooms/"
#define SHMON "/d/shadow/mon/"
#define RPMON "/d/shadow/ratpaths/mon/"
