#define SUBSTITUTIONS (["n": "%^BOLD%^%^CYAN%^%^B_BLUE%^=","s": "%^B_BLUE%^%^BOLD%^%^CYAN%^\\%^B_GREEN%^", "r": "%^B_BLUE%^%^BOLD%^%^CYAN%^/%^B_GREEN%^", "q": "%^B_BLUE%^%^BOLD%^%^WHITE%^#%^B_GREEN%^","p": "%^BOLD%^%^CYAN%^%^B_BLUE%^|%^B_GREEN%^","x": "%^B_ORANGE%^%^BOLD%^%^RED%^^%^B_BLUE%^%^BOLD%^%^WHITE%^","v": "%^B_ORANGE%^%^BOLD%^%^RED%^/%^B_BLUE%^%^BOLD%^%^WHITE%^","u": "%^B_ORANGE%^%^BOLD%^%^RED%^=%^B_BLUE%^%^BOLD%^%^WHITE%^","t": "%^B_ORANGE%^%^BOLD%^%^RED%^\\%^B_BLUE%^%^BOLD%^%^WHITE%^","y": "%^BOLD%^%^YELLOW%^%^B_GREEN%^(%^B_BLUE%^%^BOLD%^%^WHITE%^", "z": "%^BOLD%^%^YELLOW%^%^B_GREEN%^)%^B_BLUE%^%^BOLD%^%^WHITE%^","k": "%^B_GREEN%^ ", "i" : "%^BOLD%^%^YELLOW%^\\", "m": "%^BOLD%^%^YELLOW%^/%^B_BLUE%^", "I": "%^BOLD%^%^YELLOW%^/", "O": "%^BOLD%^%^YELLOW%^%^B_BLUE%^_", "o": "%^BOLD%^%^YELLOW%^%^B_GREEN%^_", "R": "%^B_BLACK%^%^RESET%^%^WHITE%^@", "S": "%^B_ORANGE%^%^BOLD%^%^YELLOW%^*","W": "%^BOLD%^%^CYAN%^~", "B": "%^B_BLUE%^%^BOLD%^%^YELLOW%^/%^BOLD%^%^WHITE%^", "b": "%^B_BLUE%^%^BOLD%^%^RED%^/%^BOLD%^%^WHITE%^", "C": "%^B_BLUE%^%^BOLD%^%^YELLOW%^_%^BOLD%^%^WHITE%^", "c": "%^B_BLUE%^%^BOLD%^%^RED%^_%^BOLD%^%^WHITE%^", "D": "%^B_BLUE%^%^BOLD%^%^YELLOW%^|%^BOLD%^%^WHITE%^", "d": "%^B_BLUE%^%^BOLD%^%^RED%^|%^BOLD%^%^WHITE%^", "E": "%^B_BLUE%^%^BOLD%^%^YELLOW%^\\%^BOLD%^%^WHITE%^", "e": "%^B_BLUE%^%^BOLD%^%^RED%^\\%^BOLD%^%^WHITE%^", "F": "%^B_BLUE%^%^BOLD%^%^YELLOW%^>%^BOLD%^%^WHITE%^", "f": "%^B_BLUE%^%^BOLD%^%^RED%^>%^BOLD%^%^WHITE%^", "G": "%^B_BLUE%^%^BOLD%^%^YELLOW%^>%^BOLD%^%^WHITE%^", "g": "%^B_BLUE%^%^BOLD%^%^RED%^<%^BOLD%^%^WHITE%^"])
#define N_BOAT ({"b e","D D","D D","DCD"})
#define NNE_BOAT ({"   c ","  B d"," B B ","B B  ","EB   "})
#define NE_BOAT ({"    cc ","  CB Cd","CB CB  ","ECB    "})
#define ENE_BOAT ({"     CCc ","  CCB CCf"," DCCCB   "})
#define E_BOAT ({" CCCCCC ","DCCCCCCf",})
#define ESE_BOAT ({" CCC    ","DCC ECC ","   ECCCf"})
#define SE_BOAT ({"       ","BEC    ","EC EC  ","  EC E ","    Ecd"}) 
#define SSE_BOAT ({"BE   ","E E  "," E E ","  Ecd"})
#define S_BOAT ({" C ","D D","D D","D D","e b"})
#define SSW_BOAT ({"   BE","  B B"," B B ","dcB  "})
#define SW_BOAT ({"     CBE","   CB CB"," CB CB  ","dcCB    "})
#define WSW_BOAT ({"     CCC ","  CCB CCD"," gCCCB   "})
#define W_BOAT ({" CCCCCC ","gCCCCCCD"})
#define WNW_BOAT ({" CCC    ","gCC ECC ","   ECCCD"})
#define NW_BOAT ({" c     ","d EC   "," EC EC ","   EC E","     EB"}) 
#define NNW_BOAT ({" c   ","d E  "," E E ","  E E","   EB"})
#define N_LOG ({"xx","xx","xx"})
#define NNE_LOG ({"  vv"," vv ","vv  "})
#define NE_LOG ({"    vv","  vv  ","vv    "})
#define ENE_LOG ({"   vuuu","uuuv   "})
#define E_LOG ({"uuuuuu",})
#define ESE_LOG ({"uutt   ","   ttuu",})
#define SE_LOG ({"tt    ","  tt  ","    tt",})
#define SSE_LOG ({"tt  "," tt ","  tt"})
#define ROCK ({"RR"})
#define N_ROCK ({"RR"})
#define NNE_ROCK ({"  RR"})
#define NE_ROCK ({"    RR"})
#define ENE_ROCK ({"     RR"})
#define E_ROCK ({"RR    ",})
#define ESE_ROCK ({"RR     ",})
#define SE_ROCK ({"RR    "})
#define SSE_ROCK ({"RR  ",})
#define N_WEIR ({"WW","WW","WW"})
#define NNE_WEIR ({"  WW"," WW ","WW  "})
#define NE_WEIR ({"    WW","  WW  ","WW    "})
#define ENE_WEIR ({"   WWWW","WWWW   "})
#define E_WEIR ({"WWWWWW",})
#define ESE_WEIR ({"WWWW   ","   WWWW",})
#define SE_WEIR ({"WW    ","  WW  ","    WW",})
#define SSE_WEIR ({"WW  "," WW ","  WW"})
#define N_SANDBAR ({"SS","SS","SS"})
#define NNE_SANDBAR ({"  SS"," SS ","SS  "})
#define NE_SANDBAR ({"    SS","  SS  ","SS    "})
#define ENE_SANDBAR ({"   SSSS","SSSS   "})
#define E_SANDBAR ({"SSSSSS",})
#define ESE_SANDBAR ({"SSSS   ","   SSSS",})
#define SE_SANDBAR ({"SS    ","  SS  ","    SS",})
#define SSE_SANDBAR ({"SS  "," SS ","  SS"})
#define ISLAND ({ "  OO  "," Ikki ","ykkkkz"," ioom "})
#define N_WATERFALL ({"ppqppqqppqppqp","qppqppqqppqppq"})
#define NNE_WATERFALL ({"qqrrqqrrqq   ","   qqrrqqrrqq",})
#define NE_WATERFALL ({"rrqr    ","  rrqr  ","    rrqr","      rr"})
#define ENE_WATERFALL ({"qqrr     "," rrqq    ","  qqrr   ","   rrqq  ","    qqrr ","     rrqq"})
#define E_WATERFALL ({"qq","==","qq","==","qq","==","qq"})
#define ESE_WATERFALL ({"    qq ","   ssqq","  qqss "," ssqq  ","qqss   "," qq    "})
#define SE_WATERFALL ({"    ssqq","   qqss "," ssqq   ","qqss    "})
#define SSE_WATERFALL ({"   ssqqssqqss","qqssqqssqq   "})
