#include "/d/common/common.h"
#define OBJD "/d/barriermnts/bforest/obj/"
#define TMONDIR "/d/barriermnts/bforest/mon/"
#define LGSW "/d/common/obj/weapon/"
#define INRMS "/d/barriermnts/bforest/rooms/"
#define IHRMS "/d/barriermnts/bforest/"
