#define OBJ "/d/azha/theater/obj/"+
#define MOB "/d/azha/theater/mons/"+
#define CALIM "/d/azha/theater/inherits/calim_inherit"
#define ROOMDIR "/d/azha/theater/rooms/"+
#define ORCH "/d/azha/theater/inherits/dso_inherit"
#define MEZZ "/d/azha/theater/inherits/mezz_inherit"
#define CALIM2 "/d/azha/theater/inherits/calim2_inherit"
#define AZP "/d/azha/theater/inherits/azha_trade"
#define CAT "/d/azha/theater/inherits/catwalk_inherit"
#define PROP "/d/azha/theater/inherits/prop_inherit"
#define COST "/d/azha/theater/inherits/cost_inherit"
#define DROOM "/d/azha/theater/inherits/droom_inherit"
#define UNDER "/d/azha/theater/inherits/under_inherit"
#define BOX "/d/azha/theater/inherits/box_inherit"
#define STAIRS "/d/azha/theater/inherits/stairs_inherit"
