mapping BLOODLINES = ([
                          "aberrant":"There is a taint in your blood, one that is alien and bizarre.",
                          "abyssal":"Generations ago, a demon spread its filth into your heritage.",
                          "accursed":"Someone cursed one of your ancestors.",
                          "arcane":"Your family has always been skilled in the eldritch art of magic.",
                          "astral":"One of your ancestors spend some time on astral plane.",
                          "boreal":"Your barbaric ancestry gives you unusual affinities.",
                          "celestial":"Someone down the line shared a bed with angels.",
                          "daemon":"A daemon lurks somewhere along your family tree.",
                          "destiny":"Your family is destined for greatness in some way.",
                          "elemental":"The power of the elements resides in you.",
                          "fey":"The capricious nature of the fey runs in your family.",
                          "ghoul":"One of your ancestors wasn't alive.",
                          "infernal":"A devil lurks in your ancestry.",
                          "protean":"Primal wilderness of chaos runs through your veins.",
                          "shadow":"Spirits from the shadow plane imparted the mystery into your bloodline.",
                          "possessed":"You have a bond with another spirit.",
                          ]);
