string * HEALS = ({"/cmds/spells/c/_cure_light_wounds.c",
            "/cmds/spells/c/_cure_moderate_wounds.c",
            "/cmds/spells/c/_cure_serious_wounds.c",
            "/cmds/spells/c/_cure_critical_wounds.c",
            "/cmds/spells/m/_mass_cure_light_wounds.c",
            "/cmds/spells/h/_heal.c",
            "/cmds/spells/m/_mass_cure_serious_wounds.c",
            "/cmds/spells/m/_mass_cure_critical_wounds.c",
            "/cmds/spells/m/_mass_heal.c"});
string * HARMS = ({"/cmds/spells/c/_cause_light_wounds.c",
            "/cmds/spells/c/_cause_moderate_wounds.c",
            "/cmds/spells/c/_cause_serious_wounds.c",
            "/cmds/spells/c/_cause_critical_wounds.c",
            "/cmds/spells/m/_mass_cause_light_wounds.c",
            "/cmds/spells/h/_harm.c",
            "/cmds/spells/m/_mass_cause_serious_wounds.c",
            "/cmds/spells/m/_mass_cause_critical_wounds.c",
            "/cmds/spells/m/_mass_harm.c"});
