#define NORTH 1
#define NORTHEAST 2
#define EAST 3
#define SOUTHEAST 4
#define SOUTH 5
#define SOUTHWEST 6
#define WEST 7
#define SOUTHWEST 8
#define WALL_NS "|"
#define WALL_EW "-"
#define WALL_NESW "\\"
#define WALL_NWSE "/"
#define DOOR "D"
