#define TEC "/realms/lujke/tecqumin/"
#define GUARD_STEP "/realms/lujke/tecqumin/rooms/guardstep.c"
#define MOB "/realms/lujke/tecqumin/mons/"
#define OBJ "/realms/lujke/tecqumin/obj/"
#define ROOMS "/realms/lujke/tecqumin/rooms/"
#define STEP_LOW "/realms/lujke/tecqumin/rooms/step_low.c"
#define STEP_MID "/realms/lujke/tecqumin/rooms/step_mid.c"
#define STEP_HIGH "/realms/lujke/tecqumin/rooms/step_high.c"
#define ZIG "/realms/lujke/tecqumin/rooms/zig.c"
#define ZIG_INT_BASE "/realms/lujke/tecqumin/rooms/zig_int_base.c"
#define ZIG_LOW "/realms/lujke/tecqumin/rooms/zig_low.c"
#define ZIG_MID "/realms/lujke/tecqumin/rooms/zig_mid.c"
#define ZIG_HIGH "/realms/lujke/tecqumin/rooms/zig_high.c"
#define ZIG_HIGHEST "/realms/lujke/tecqumin/rooms/zig_highest.c"
#define MAZE "/realms/lujke/tecqumin/maze/mazebase.c"
#define MAZEROOMS "/realms/lujke/tecqumin/maze/"
#define PHASE_MON "/realms/lujke/tecqumin/mons/phase_mon.c"
#define HUNT_MON "/realms/lujke/tecqumin/mons/hunt_mon.c"
#define LOW_MAZE "/realms/lujke/tecqumin/rooms/low_maze"
#define CULT_ITEM "/realms/lujke/tecqumin/obj/cultural_items.c"
#define SCANNER "/realms/lujke/obs/far_scanner2.c"
#define DESTROOM "/realms/lujke/tecqumin/rooms/destination_room.c"
#define GHOST_PRIEST "/realms/lujke/tecqumin/mons/ghost_warrior.c"
#define CORRIDOR "/realms/lujke/tecqumin/rooms/corridor.c"
#define TUNBASE "/realms/lujke/tecqumin/rooms/tunbase.c"
#define JUNG "/realms/lujke/tecqumin/jungle/"
#define JUNG_ROOM "/realms/lujke/tecqumin/jungle/rooms/"
#define JUNG_ROOM1 "/realms/lujke/tecqumin/junglea/rooms/"
#define JUNG_ROOM2 "/realms/lujke/tecqumin/jungleb/rooms/"
#define JUNG_ROOM3 "/realms/lujke/tecqumin/junglec/rooms/"
#define JUNG_ROOM4 "/realms/lujke/tecqumin/jungled/rooms/"
#define JUNG_ROOM5 "/realms/lujke/tecqumin/junglee/rooms/"
#define JUNG_ROOM6 "/realms/lujke/tecqumin/junglef/rooms/"
#define JUNG_ROOM7 "/realms/lujke/tecqumin/jungleg/rooms/"
#define JUNG_ROOM8 "/realms/lujke/tecqumin/jungleh/rooms/"
#define J_MAZE "/realms/lujke/tecqumin/jungle/rooms/jung_base.c"
#define PLAT_BASE "/realms/lujke/tecqumin/treehouse/rooms/platform_base.c"
#define TEST "/realms/lujke/tecqumin/test/"
#define QNPC "/d/npc/QNPC.c"
#define BUILDER "/d/atoyatl/maze_d.c"
#define WEMIC "/realms/lujke/wemic/rooms/"
#define TREEHOUSE "/realms/lujke/tecqumin/treehouse"
#define TABAXROOM "/realms/lujke/tecqumin/tabaxi/rooms/"
#define TABAXOBJ "/realms/lujke/tecqumin/tabaxi/obj/"
#define LOW_FIELD 1
#define MAIN_FIELD 2
#define HIGH_FIELD 3
#define NO_TARGET 0
#define OIL 1
#define ROCKS 2
#define WATERYLIQUID 3
#define SAND 4
#define LOG "/realms/lujke/tecqumin/log/"
#define CAMOUFLAGE "%^GREEN%^c%^ORANGE%^a%^GREEN%^mou%^BOLD%^%^GREEN%^f%^RESET%^%^GREEN%^l%^ORANGE%^a"\
                   +"%^GREEN%^ge%^RESET%^"
#define CAMOUFLAGED "%^GREEN%^c%^ORANGE%^a%^GREEN%^mou%^BOLD%^%^GREEN%^f%^RESET%^%^GREEN%^l%^ORANGE%^"\
                   +"a%^GREEN%^g%^BOLD%^%^GREEN%^e%^RESET%^%^GREEN%^d%^RESET%^"
#define CAMOUFLAGING "%^GREEN%^c%^ORANGE%^a%^GREEN%^mou%^BOLD%^%^GREEN%^f%^RESET%^%^GREEN%^"\
                   +"l%^ORANGE%^a%^GREEN%^g%^BOLD%^%^GREEN%^i%^RESET%^%^GREEN%^ng%^RESET%^"
#define RAM 0
#define WAIT 1
#define SWING 2
#define LADDER 3
#define STOPPED 4
#define ARCHERY 5
#define WALK_IN 6
#define REGROUPING 7
#define CLIMB 8
