#define CWP "/d/common/obj/weapon/"+

static mapping VALID_WP_TYPES = ([
"awlpike" : CWP"awlpike",
"bardiche" : CWP"bardiche",
"bastard sword" : CWP"bastard",
"battle axe" : CWP"battle_axe",
"bec de corbin" : CWP"bec_de_corbin",
"broad sword" : CWP"broad",
"claw" : CWP"claw",
"club" : CWP"club",
"dagger" : CWP"dagger",
"double axe" : CWP"double_axe",
"double bladed sword" : CWP"double_bladed_sword",
"fan" : CWP"fan",
"fauchard" : CWP"fauchard",
"flail" : CWP"flail",
"halberd" : CWP"halberd",
"hammer" : CWP"warhammer",
"hand axe" : CWP"handaxe",
"heavy horse lance" : CWP"hhlance",
"jousting lance" : CWP"jlance",
"katana" : CWP"katana",
"khopesh sword" : CWP"khopesh",
"knife" : CWP"knife",
"medium horse lance" : CWP"lance",
"light horse lance" : CWP"lhlance",
"rapier" : CWP"rapier",
"long sword" : CWP"longsword",
"lucern hammer" : CWP"lucern_hammer",
"mace" : CWP"mace",
"military fork" : CWP"military_fork",
"morningstar" : CWP"morningstar",
"spear" : CWP"mspear",
"staff" : CWP"quarter_staff",
"partisan" : CWP"partisan",
"pick" : CWP"pick",
"scimitar" : CWP"scimitar",
"whip" : CWP"whip",
"scythe" : CWP"scythe",
"shortsword" : CWP"shortsword",
"sickle" : CWP"sickle",
"spetum" : CWP"spetum",
"trident" : CWP"trident",
"voulge" : CWP"voulge",
"wakizashi" : CWP"wakizashi",
"whip dagger" : CWP"whip_dagger",
"two handed sword" : CWP"two_hand_sword",
"bill-guisarme" : CWP"bill-guisarme",
]);

static mapping VALID_WP_SUBTYPES = ([
"bastard sword" : ([ 3 : CWP"bastard_two", 4 : CWP"giant_bastard"]),
"club" : ([ 2 : CWP"mclub", 3 : CWP"club_lg", 4 : CWP"giant_club"]),
"battle axe" : ([ 3 : CWP"large_battle_axe", 4 : CWP"giant_battle_axe"]),
"hammer" : ([ 1 : CWP"hammer_sm", 3 : CWP"hammer_lg", 4 : CWP"giant_hammer"]),
"mace" : ([ 4 : CWP"giant_mace"]),
"morningstar" : ([ 4 : CWP"giant_morningstar"]),
"rapier" : ([ 1 : CWP"light_rapier" ]),
"staff" :  ([ 1 : CWP"sstaff", 2 : CWP"staff"]),
"spear" : ([ 1 : CWP"spear_sm", 3 : CWP"spear_lg"]),
"scythe" : ([ 3 : CWP"two_hand_scythe" ]) 
]);
