#define BASE "/d/islands/common/aramanth/inherit/mountain"
#define ARAMANTH "/d/islands/common/aramanth/room21"
#define MOUNTAIN "/d/islands/common/aramanth/"
#define MON "/d/islands/common/mon/"
#define WEP "/d/islands/common/obj/"
#define OBJ "/d/islands/common/obj/"
